### ISSUE TITLE
Clarify use of 'Allow forwarded traffic'

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/architecture-center#1051]
In the VNet Peering section, the doc states:

You can also configure spokes to use the hub VNet gateway to communicate with remote networks. To allow gateway traffic to flow from spoke to hub, and connect to remote networks, you must:
- Configure the VNet peering connection in the hub to allow gateway transit.
- Configure the VNet peering connection in each spoke to use remote gateways.
- Configure all VNet peering connections to allow forwarded traffic.

The third bullet is wrong. 'Allow forwarded traffic' is not required to transit traffic through a VPN gateway (I just tried it).

I believe 'Allow forwarded traffic' is only required in the scenario described in the preceding paragraph, where traffic is routed via an NVA in a hub-spoke architecture.

The doc should be clarified to properly explain the use of 'allow forwarded traffic' in each scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Implement a hub-spoke network topology in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/hub-spoke.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by mike-urnun-msft** [comment]
Hi @jtuliani Thank you for reporting this issue! We will review and make any necessary changes.

**Comment by stewartadam** [comment]
+1, I would also add that we should note that when enabling forwarded traffic on the VNet, users need to consider that the Azure NICs also need to have forwarding enabled (we can simply link to [here](https://docs.microsoft.com/en-us/azure/virtual-network/tutorial-create-route-table-portal#turn-on-ip-forwarding)).

I spend lots of time trying to figure out why my Linux VM's couldn't reach each other following this guide until I realized there was an extra setting on the NICs to enable too.

**Comment by doodlemania2** [comment]
Thank you so much - this item has been moved to our internal backlog for documentation refinement.

**Comment by evandropomatti** [comment]
@doodlemania2 the [documentation ](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#recommendations)still states that "allow forwarded traffic" is required. Judging by @jtuliani testing it should not, and the documentation should be changed.

Is it in fact required and his test was somewhat incorrect? Or the documentation needs to updated?

> 
> You can also configure spokes to use the hub gateway to communicate with remote networks. To allow gateway traffic to flow from spoke to hub, and connect to remote networks, you must:
> 
>- Configure the peering connection in the hub to **allow gateway transit**.
>- Configure the peering connection in each spoke to use **remote gateways**.
>- Configure all peering connections to **allow forwarded traffic**.

I also suggest that we don't close the issue here until it is done. The internal process doesn't matter to the community, otherwise we just run into situations like this.

**Comment by ferantivero** [comment]
thanks for sharing this feedback @jtuliani and @evandropomatti, we really appreciate this 😸

I think that this refers to the [Virtual Network Peering](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke#virtual-network-peering) section under Recommendations where based on my understanding, two different scenarios are being discussed.  

#### Scenario A
If you require spokes to connect to each other without peering them. 

For this case scenario, please let us share from the [Create a peering](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-peering#create-a-peering) docs the following: 

_"If this checkbox is not checked for the peering between each spoke virtual network and the hub virtual network, traffic doesn't flow between the spoke virtual networks because the hub is not forwarding the traffic between the virtual networks."_

Additionally, 

_"You don't need to check this setting if traffic is forwarded between virtual networks through an Azure VPN Gateway."_

#### Scenario B
Configure spokes to use the hub gateway to communicate with remote networks. For this very particular configuration, *Allow forwarded traffic* is not required.

That being said, please let us re-open this issue since I agree while reading the docs that this is good idea to make a distinction in here.
 
As part of this revision, please let's also consider to indicate on which peering these checks are really required (i.e. Scenario B, `[x] Use remote gateways` is required from spoke-hub peering, while `[x] Allow gateway transit` is required from hub-spoke peering, and `[] Allow forwarded traffic` could remain un-checked for both) provided that is the author's preference. A side by side view of this might be ideal.

Just to conclude and in all fairness, current configuration will work well for both scenarios A + B, so they are not conflicting each other. Given that, for the sake of simplicity we might want to keep the ARM(s) as-is for now.

**Comment by evandropomatti** [comment]
@ferantivero I think you nailed it and we can close the issue now.
