### ISSUE TITLE
Please adjust width of table

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/architecture-center#1343]
@KeiroKamioka0000 commented on [Sun Feb 24 2019](https://github.com/mspnp/architecture-center.ja-jp/issues/32)

https://docs.microsoft.com/ja-jp/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions

As you may notice, please consider to edit the width of table,
It really hard to read.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Azure リソースの名前付け規則 - Best practices for cloud applications](https://docs.microsoft.com/ja-jp/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center.ja-jp/blob/live/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

---

@CeciAc commented on [Mon Feb 25 2019](https://github.com/mspnp/architecture-center.ja-jp/issues/32#issuecomment-467120241)

Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@CeciAc commented on [Thu Mar 07 2019](https://github.com/mspnp/architecture-center.ja-jp/issues/32#issuecomment-470534445)

Hi Isha
I'm assigning this one to you since is out of our scope.

Kind regards,
Microsoft DOCS International Team

---

@ishasahni1 commented on [Thu Mar 07 2019](https://github.com/mspnp/architecture-center.ja-jp/issues/32#issuecomment-470763686)

@CeciAc 

Please open a source issue or PR, for this topic writer, as they can help in addressing this issue.

---

@KeiroKamioka0000 commented on [Thu Mar 07 2019](https://github.com/mspnp/architecture-center.ja-jp/issues/32#issuecomment-470767261)

I think I verify the fix for this document.
I assuming it fixed with similar post I made in another document.

**Comment by CeciAc** [comment]
Hi team,
I'm moving this one here as per @ishasahni1 comment above
this is not a loc issue

**Comment by mike-urnun-msft** [comment]
Hi @CeciAc Thank you for your feedback! We will review and update as appropriate.

**Comment by Powerhelmsman** [comment]
@mike-urnun-msft Please assign it to @sudeepku. He is managing Docs GitHub issue now.

**Comment by sudeepku** [comment]
@CeciAc, I  examined the issue in details. The scroll bar appearing in some of the tables on this page https://docs.microsoft.com/ja-jp/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions is primarily because of  (a) number of columns in the table (b)  a natural text expansion upon translation for some languages. With our UI design we try to minimize the readability impact in non-English languages, it is sometimes simply too hard to achieve for all cases.  The same topic in Chinese does not have the scroll bar for the tables, (https://docs.microsoft.com/zh-cn/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions) , whereas the topic in German (https://docs.microsoft.com/de-de/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions)  has scrollbars similar to Japanese topic you reported.

I have communicated the feedback to our engineering team to look into ways of how we can improve the reading experience for non-English languages.
