### ISSUE TITLE
The article does not show how to retrieve Secrets from Key Vault

### ISSUE THREAD

**Issue by ricardoserradas** [MicrosoftDocs/architecture-center#1492]
The article does not finish showing how to retrieve some value from the Azure Key Vault using C#.

I would expect this article to show the app connecting to the Database using the connection string directly from Azure Key Vault, for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5df2491-1abe-0211-efbf-c1fb384862e9
* Version Independent ID: f7f0d2cf-3f4f-44dc-54aa-cd59221264d2
* Content: [Use Key Vault to protect application secrets](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/key-vault)
* Content Source: [docs/multitenant-identity/key-vault.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/key-vault.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by ricardoserradas** [comment]
A good article that we could use as an example or reference it:

https://www.humankode.com/asp-net-core/how-to-store-secrets-in-azure-key-vault-using-net-core

**Comment by DixitArora-MSFT** [comment]
@ricardoserradas Thanks for the feedback. I have assigned this to content author to review and update as appropriate.

**Comment by ricardoserradas** [comment]
> @ricardoserradas Thanks for the feedback. I have assigned this to content author to review and update as appropriate.

Cool, thanks!

I'm also working on a general DevOps guidance on GitHub and I worked on creating some samples for .NET Core + KeyVault to cover some security stuff that you could leverage, if you want:

https://github.com/ricardoserradas/feat-flag-sample/blob/master/docs/01-key-vault.md

**Comment by MikeWasson** [comment]
@ricardoserradas Thanks for the feedback. I think the title of this article is misleading. It's not really about how to "use Azure Key Vault to protect application secrets". Rather, it's specifically about how the Tailspin reference implementation (described [here](https://docs.microsoft.com/azure/architecture/multitenant-identity/tailspin)) uses Key Vault. I will update the article so that the context and intent is clearer. 

You can find an end-to-end tutorial on using Key Vault in .NET here: https://docs.microsoft.com/azure/key-vault/tutorial-net-create-vault-azure-web-app
