### ISSUE TITLE
Multi-Region Deployment - If user base is in Asia and US

### ISSUE THREAD

**Issue by ashishmundrajll** [MicrosoftDocs/architecture-center#1533]
We have equal amount of users in Asia and US, and if we select HongKong as Primary Region, then will it be slower Performance for users in USA to access our sites? 

I am looking for a Pattern which supports both cross-region availability and disaster recovery. Azure SQL is the backend but its secondary replica is read-only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@ashishmundrajll Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by ashishmundrajll** [comment]
Here it is - https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region
In this deployment there will be a latency which users from US will face if Primary Region is HK. If Azure SQL can support Multi-master (master - master replication), this may work. 

AWS has some multi-master feature but I only glanced over it, not sure if that is relevant.

**Comment by KetanChawda-MSFT** [comment]
@ashishmundrajll This reference architecture focuses on active/passive with hot standby, using Traffic Manager for failover. You can configure Traffic Manager as with the geographic traffic routing method to direct traffic to specific endpoints based on the geographic location where the requests originate.

Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
