### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by taromielnaz** [MicrosoftDocs/architecture-center#1636]
In the Architecture section, this sentence  "The application is deployed to each region", does it mean manually or automatically? If a web app changes a lot, do we have to apply the updates on all web apps in other regions? Or are they synced automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c0c2a8-94a0-67ef-602a-6013bc7aa403
* Version Independent ID: 27705eeb-7853-bd5d-58ac-a07bd6a8a79d
* Content: [Highly available multi-region web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/multi-region#feedback)
* Content Source: [docs/reference-architectures/app-service-web-app/multi-region.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/multi-region.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@taromielnaz Thanks for the query! We will get back to you on this.

**Comment by PramodValavala-MSFT** [comment]
@taromielnaz Yes. You would have to manually deploy them since they are all separate entities resources.

Ideally, you would want to setup [continuous deployment using git](https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment) for production scenarios, which would take care of deployment to all regions.

As for creating the app service resources themselves, you could use [ARM templates with loops](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-multiple) for creating identical copies.

And if you are using [App Service on Linux](https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-intro) with [containers](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image), you would just push a new container which should be picked up automatically if [continuous deployment for containers](https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-ci-cd?toc=%2fazure%2fapp-service%2fcontainers%2ftoc.json) is setup.

**Comment by taromielnaz** [comment]
Thanks, @PramodValavala-MSFT. It can be closed now.
