### ISSUE TITLE
Comprehensive

### ISSUE THREAD

**Issue by ashishjain87** [MicrosoftDocs/architecture-center#1738]
I found this document to be comprehensive, beautifully written (with examples to clarify each point) and very useful. Great job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad651d6a-f8d8-2050-e7a7-adbae7326112
* Version Independent ID: 4fddd724-cabd-8623-7692-857088c1dccb
* Content: [API design guidance - Best practices for cloud applications](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#feedback)
* Content Source: [docs/best-practices/api-design.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/best-practices/api-design.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@ashishjain87 Thanks for the kudos and sharing your feedback and thoughts on this matter. Surely, it'll benefit others visiting thread.

We will now proceed to close this thread for now since this channel is more for fixing issues in the scope of the documentation and driving improvements towards it. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
