### ISSUE TITLE
Visio Files

### ISSUE THREAD

**Issue by knssub** [MicrosoftDocs/architecture-center#1749]
hi, The article is one of the best-written article in the Azure documentation. Very comprehensive. It will be very helpful if you could provide us with the Visio files. It takes humongous time to replicate this in the Visio :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d8a578-f9f1-53af-64d0-808f1fde6c9c
* Version Independent ID: 8a647cb7-2d10-53ed-5459-4356ef607e77
* Content: [Azure virtual datacenter: A network perspective](https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter#feedback)
* Content Source: [docs/vdc/networking-virtual-datacenter.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/vdc/networking-virtual-datacenter.md)
* Service: **cloud-adoption-framework**
* Sub-service: **reference**
* GitHub Login: @tracsman
* Microsoft Alias: **jonor**

**Comment by KetanChawda-MSFT** [comment]
@knssub Thanks for the kudos and sharing your feedback and thoughts on this matter. Surely, we will take this as a opportunity and see if that is feasible. For few of the architecture it is available. See this [document](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/vpn).

You can download the Azure Cloud and AI Symbol / Icon Set - SVG from [here](https://www.microsoft.com/en-us/download/details.aspx?id=41937).

We will now proceed to close this thread for now since this channel is more for fixing issues in the scope of the documentation and driving improvements towards it. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
