### ISSUE TITLE
Role of Azure Load Balancer

### ISSUE THREAD

**Issue by snake-net** [MicrosoftDocs/architecture-center#1797]
Could you please elaborate what is the role and benefits of the Azure Load Balancer in that scenario? As far as I know, it is also possible to expose Ingress Controller directly to consumers. Why is it recommended to have LB in front of it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5e2e444-d6b9-962e-56d4-8d1f3508ba9e
* Version Independent ID: 061ea6aa-353b-a98d-cbf6-639209a5fd1b
* Content: [Microservices architecture on Azure Kubernetes Service (AKS)](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/microservices/aks#security-considerations)
* Content Source: [docs/reference-architectures/microservices/aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/microservices/aks.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by PramodValavala-MSFT** [comment]
@snake-net An ingress controller (like nginx-ingress) still runs on the cluster as a daemonset, so there is an instance running on each node. Now, as your cluster scales, you would have multiple nodes through which you can access the ingress endpoint running on your cluster.

And instead of loading all ingress traffic through one node, an Azure Load Balancer would help route traffic equally among the nodes.

Also, this way, your nodes (the VMs) don't have to be exposed directly to the internet as well.

**Comment by snake-net** [comment]
That is clear now. Thank you!

**Comment by PramodValavala-MSFT** [comment]
@snake-net Glad that we could help!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by mohanM5k** [comment]
@PramodValavala-MSFT 
FYI, I am a lerner-beginner.
I am a bit confused about LB. is this an old way of implementation. why are we not using API gateway that has both load balancer and WAF.  If we can use API gateway as an Ingress controller(Application Gateway Ingress Controller (AGIC)), we can expose API gateway right? (internally i can use API management PAAS service to map the different APIs from AKS). Please elaborate?

**Comment by PramodValavala-MSFT** [comment]
@mohanM5k Not really. It mostly comes down to choice.

With AGIC, like [their docs](https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview) mention, it eliminates the need for a load balancer since it handles both load balancing (between K8s nodes) and ingress for your services. So, as long as your all of your clusters are on Azure, AGIC is indeed a great way to go about it to simplify your infrastructure.

Without AGIC however, you would need separate services that perform both load balancing and ingress, where many use in-cluster solutions like nginx-ingress or even APIM directly running within K8s and a platform specific load balancing depending on where K8s is hosted. This is more platform agnostic since in-cluster solutions don't depend on where/how your K8s clusters are hosted.

I hope that helps clarify your query. Since this is an old post, it would be best to create a new post on [Microsoft Q&A](https://docs.microsoft.com/answers) to engage the wider community, if you have any further queries.
