### ISSUE TITLE
Security Best Practices  questions - is it already secure as proposed or we need more security assets in place?

### ISSUE THREAD

**Issue by joslat** [MicrosoftDocs/architecture-center#1829]
This components are already secure due to the fact of having HTTPS (SSL enforced) and AD authentication? or would it be convenient to add a subnet with NSG on the non visible to internet assets (resource group, SQL azure, etc...)? and would a App Gateway with WAF or Azure Frontdoor be convenient to add security?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84bcf722-abb3-69b8-8073-15ae4a6890de
* Version Independent ID: 7b2010c6-696d-de66-8e56-8ac5d3e54526
* Content: [Basic web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app#feedback)
* Content Source: [docs/reference-architectures/app-service-web-app/basic-web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/app-service-web-app/basic-web-app.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by ChiragMishra-MSFT** [comment]
@joslat Thanks for reaching out. We are currently investigating into the issue and will update you shortly.

**Comment by joslat** [comment]
Hi Chirag, thanks for responding. My question does not report any "issue". I am just asking how much secure is this "reference implementation" with just SSL and Azure AD authentication.

**Comment by PramodValavala-MSFT** [comment]
@joslat Web Apps deployed to Azure App Service are already heavily secured since most of the underlying services like VMs, Storage, Network, etc. are abstracted and list in this doc do mention security you can add at the application level. Also, the [app service security doc](https://docs.microsoft.com/en-us/azure/app-service/overview-security) has more ways to further secure your app.

As for protecting non-azure services, placing them in VNETs (with NSGs) is indeed more secure. Do note that you might have to change tiers depending on the service you are using for deploying them into a VNET.

Some services support [VNET Service Endpoints](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview) and App Service supports [VNET Integration](https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet).

Another way to protect other resources is by using features like [Managed Identity](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity) for authentication for calls from your app service to other resources.

**Comment by PramodValavala-MSFT** [comment]
@joslat Just following up here... Hope my previous comment helps.

Since there is no doc update required here, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
