### ISSUE TITLE
auto action mail - add variables to subject

### ISSUE THREAD

**Issue by Jarnstrom** [MicrosoftDocs/architecture-center#1868]
is requesting that the subject in auto generated mail contains: resourcename, alert rule and ticketID. Similar to the resolved alert mail which is
Alert Resolved for entity: "resourcename", Alert Rule 'Alert rule name', Ticket: '11111'

In the short run maybe default subject would be similar to the above and can be overruled while creating the auto action and in the long run there is a set of varibles that can be used while creating the auto action.

**Comment by mike-urnun-msft** [comment]
Hi @Jarnstrom - Thank you for your feedback. Since this channel is more for driving improvements towards MS Docs, could you provide us with a URL of the documentation that your feedback is most applicable to? That way, we're able to locate the right team that's better suited to address your feedback.
