### ISSUE TITLE
script fails.

### ISSUE THREAD

**Issue by nikhillotia** [MicrosoftDocs/architecture-center#1870]
When I try run the below command 
azbb -s <subscription_id> -g ra-onprem-sp2016-rg -l <location> -p onprem.json --deploy
I get this error

azbb -s "xxxxxx-xxxxx-xxxxx-xxxx-xxxxxx" -g onprem-vnet-rg -l eastus -p .\shared-services-stack.json --deploy

  error: error executing az
  message:
  status: null
  arguments: vm list-skus --resource-type virtualMachines --zone false --subscription 6xxxxx-xxxx-xxxxx-xxxxxx-xxxxx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d93eb87-54cb-cf38-dfae-0ebe7579d608
* Version Independent ID: c7ac665e-d194-ab07-c1bb-5d5a3049c5ec
* Content: [Run a highly available SharePoint Server 2016 farm in Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/)
* Content Source: [docs/reference-architectures/sharepoint/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/sharepoint/index.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @njray
* Microsoft Alias: **pnp**

**Comment by AshokPeddakotla-MSFT** [comment]
@nikhillotia  Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by nikhillotia** [comment]
Please find docment link:
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/sharepoint/
Facing issue during deployment steps  in first command.

azbb -s <subscription_id> -g ra-onprem-sp2016-rg -l <location> -p onprem.json --deploy

**Comment by PramodValavala-MSFT** [comment]
@nikhillotia Looks like the error has been [reported already](https://github.com/mspnp/template-building-blocks/issues/418), which you have found as well. 

Also, there is [a PR](https://github.com/mspnp/template-building-blocks/pull/420) open to address this as well. @MikeWasson Could we get someone assigned for this PR?

As a workaround before the PR is merged, if you'd like, you could try the following

> You would require having `git` and `nodejs` installed for these steps

1. Clone the repo

```sh
git clone https://github.com/mspnp/template-building-blocks.git
```

2. Run `npm install`
3. Make the code change as mentioned in the PR
3. Run the same command as you've tried before, except replace `azbb` with `node ./src/index.js`

Since there is no doc update required here, we will now proceed to close this thread.
