### ISSUE TITLE
Azure Devops CI/CD For Aks

### ISSUE THREAD

**Issue by partha-sarathi-sarkar** [MicrosoftDocs/architecture-center#1888]
I have been going through the docs of CI/CD for AKS using azure pipeline.

There are certain docs for CI/CD but those are based on yaml file. 

I have successfully deployed to AKS from Azure CI/CD with Azure devops classic editor pipeline.

I didn't get any docs regarding CI/CD using classic editor. So I am Prepared some docs for the Pipeline process . Is there any changes for approval if i Send a PR for the CI CD process for deploying app to aks .?
Let me know if its relevant then i will contribute .

**Comment by MarileeTurscak-MSFT** [comment]
@partha-sarathi-sarkar to clarify, are you hoping to make pull requests to existing docs? Can you please link those docs here? 

The guide for contributing is here: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by PramodValavala-MSFT** [comment]
@partha-sarathi-sarkar Just following up here... Feel free to take a look at the contributing guide shared and create the PR. Once the PR is created, the assigned reviewer would help you further by providing feedback and walk you through in getting the doc merged.

**Comment by PramodValavala-MSFT** [comment]
@partha-sarathi-sarkar Hope you were able to work up a PR from the links shared.

Since there is no doc related feedback to address here, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
