### ISSUE TITLE
Visio link is wrong

### ISSUE THREAD

**Issue by elliot-labs** [MicrosoftDocs/architecture-center#1920]
The link to the Visio doc at teh top of the page appears to go to the Identity Architectures ref arch rather than this ref arch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend your on-premises Active Directory domain to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by elliot-labs** [comment]
The wrong Visio file is specifically from:
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adfs

**Comment by ketan-chawda-msft** [comment]
@elliot-labs Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@elliot-labs The visio link is correct. The downloaded vsdx file contains all the reference architectures. You need to switch the tabs in the bottom of your visio file as shown below:

![image](https://user-images.githubusercontent.com/59500871/72411939-1da00280-3792-11ea-9443-4102f681483c.png)

Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by elliot-labs** [comment]
Good catch, this was my first time using Visio. I didn't see the tabs.
Thank you for the fast response :)
