### ISSUE TITLE
Visio Link is Wrong

### ISSUE THREAD

**Issue by elliot-labs** [MicrosoftDocs/architecture-center#1922]
The link to the Visio doc at the top of the page goes to the wrong Ref Arch.

The wrong Visio file is specifically from:
https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adfs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9383c21-9143-1559-c1a8-e6f6dc830159
* Version Independent ID: 37c6c659-a6bc-633e-2b3f-337deb01c215
* Content: [Integrate on-premises AD domains with Azure AD - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/azure-ad)
* Content Source: [docs/reference-architectures/identity/azure-ad.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/identity/azure-ad.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KrishnaG-MSFT** [comment]
@elliot-labs Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@elliot-labs The visio link is correct. The downloaded vsdx file contains all the reference architectures. You need to switch the tabs in the bottom of your visio file as shown below:

![image](https://user-images.githubusercontent.com/59500871/72411939-1da00280-3792-11ea-9443-4102f681483c.png)

Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by elliot-labs** [comment]
Good catch, this was my first time using Visio. I didn't see the tabs.
Thank you for the fast response :)
