### ISSUE TITLE
Visio file download is different to the diagram

### ISSUE THREAD

**Issue by andyturn31** [MicrosoftDocs/architecture-center#1932]
Hi
The first diagram in this article has a link to download a visio file.  Problem is the file which gets downloaded is different to the image shown in the diagram.
Could this be changed?
Thanks
:-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c1b093-200e-8d59-0e6e-98f510dca5f6
* Version Independent ID: db6fcf0f-1a88-b216-4c08-a83c4128b4fa
* Content: [Connect an on-premises network to Azure using ExpressRoute - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by ketan-chawda-msft** [comment]
@andyturn31 Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by ketan-chawda-msft** [comment]
@andyturn31 The visio link is correct. The downloaded vsdx file contains all the reference architectures. You need to switch the tabs in the bottom of your visio file as shown below:

![image](https://user-images.githubusercontent.com/59500871/72554693-3529d900-38c1-11ea-9767-e9045991ddad.png)

Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by andyturn31** [comment]
Thanks for pointing this out lol.
:-)
