### ISSUE TITLE
How would that work in case there is some common components

### ISSUE THREAD

**Issue by micheleissa** [MicrosoftDocs/architecture-center#2014]
Let's say the code has some common features that more than one service is using. How would such a thing work in the CI/CD mentioned here?
Also is it possible to have another docs for Gitflow instead of trunk based development?
In the Github repo, there is one pipeline for each micro-service. Would it be better to have a gated build for branch code to run everything including unit tests and docker-compose to validate the PR content and then once the pr is approved develop branch build kicks in and do the same plus pushing images to Container Registry and publishing the artifacts for later use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f4d213-3eb1-5b4c-aa67-116e8fa36f7d
* Version Independent ID: 18199b5a-8f57-6574-c795-7540199ae49a
* Content: [Building a CI/CD pipeline for microservices on Kubernetes - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/ci-cd-kubernetes?source=docs)
* Content Source: [docs/microservices/ci-cd-kubernetes.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/ci-cd-kubernetes.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by micheleissa** [comment]
Any news on this??

**Comment by absheik** [comment]
@micheleissa we are tracking this ask in our backlog.  Would be able to submit a pr for your ask to leverage GitFlow instead of trunk.

**Comment by ferantivero** [comment]
thanks for your questions @micheleissa, they are very appropriate and hopefully the answers could help to articulate concepts scattered in some articles from this guidance 😸  

First and foremost please note that in CI/CD there is not such one-size-fits-all approach. It means, every team might have different needs, and at the end of the day that is what should drive decisions around this field. 

>> Let's say the code has some common features that more than one service is using. How would such a thing work in the CI/CD mentioned here?

this could potentially refer to a microservices architecture where `shared code` between multiple microservices is required somehow. In this particular guidance prevails the idea in which every microservice team should be able to deploy independently at their own pace. In other words, there is no such trigger that could automatically deploy a bunch of services when `shared code` gets updated. But, how could this even work in this scenario?
- shared code maintainers will be responsible for not breaking functionality that they are providing with.
- when shared code gets deprecated, the microservice team will be responsible for making the arrangements to deploy a new release, otherwise the service will be out of game.

>> Also is it possible to have another docs for Gitflow instead of trunk based development?

Before answer this question specifically, please let's go back one moment over the microservices context, in some cases (not all) being able to release really fast could be critical. It means, teams might want to release on top of every feature they push to their services, and git-flow in that aspect could slow things a bit down. Of course there are products out there in which maturity of the release, support multiple versions, etc. are more important than just blazing fast deployments.

That said, the answer is, it'd be ideal to also have such doc. Not quite sure whether this could apply to this specific guidance. But I plan to mention this to the team 📣 

In the meantime, please let me share 2 resources you may find interesting:
1. [Release Flow](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow), when maturity is important, side by side versions and more, it's trunk based though.
2. [blog post](https://nvie.com/posts/a-successful-git-branching-model/) that introduces git-flow with a recent important update note from its author.

>> In the Github repo, there is one pipeline for each micro-service. Would it be better to have a gated build for branch code to run everything including unit tests and docker-compose to validate the PR content and then once the pr is approved develop branch build kicks in and do the same plus pushing images to Container Registry and publishing the artifacts for later use?  

these pipelines do build incrementally depending on the branch  (feature/topic/trunk/release). But please let us detail the process a bit more below:

1. if a new commit is pushed to a `feature` or `topic` branch, a new build kicks-in but it's partial one that will only the run unit tests using a multistage Docker image targeting an intermediate layer.
2. merging to the `trunk`, will kick off another build containing some extra steps like build the runtime Docker image. 
3. when pushing to a `release` branch, then it will execute a full-ci pipeline: runtime Docker image is created + the Docker image & helm package are pushed to the Azure Container Registry + Azure Pipeline artifact is published

Please let us close this issue for now. But please do not hesitate in re-open this or create new one(s) asking for more support.
