### ISSUE TITLE
The download content of the Visio file is not reflecting the diagram in the page

### ISSUE THREAD

**Issue by paulsjs** [MicrosoftDocs/architecture-center#2020]
Hi, 
(I also saw similar feedback in the closed section which was not answered back by the user).
The content of the Visio file, which can be download in the top section of this page, just below the diagram, will download a file called hybrid-network-architectures.vsdx and includes "Azure Stack" components!
This is not the diagram (expressroute-vpn-failover.png) which is displayed on the actual page above!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec640d8-1064-c083-4313-5e8c23fbc2cf
* Version Independent ID: 5f7c63ca-7ab2-9129-4c34-191286e67af1
* Content: [Connect an on-premises network to Azure using ExpressRoute - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/expressroute-vpn-failover#feedback)
* Content Source: [docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/hybrid-networking/expressroute-vpn-failover.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by ketan-chawda-msft** [comment]
@paulsjs  The visio link is correct. The downloaded vsdx file contains all the reference architectures. You need to switch the tabs in the bottom of your visio file as shown below:

![image](https://user-images.githubusercontent.com/59500871/76492511-6f919b80-6456-11ea-9b99-1fe0feb49167.png)


Since there is no doc update required at the moment, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by paulsjs** [comment]
Sorry I missed the tabs. Thanks for the quick answer!!
