### ISSUE TITLE
Is it decentralized or distributed?

### ISSUE THREAD

**Issue by pascalandy** [MicrosoftDocs/architecture-center#2021]
Hi,

Can you share the definition of "decentralize"?

[I saw your post](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/decentralized-trust) and it looks we are mixing the definitions. Decentralize is not a two-way synonym of:

- consortium of organizations
- sharing data
- distributed ledger tech (DLT)

I agree with this statement:

> With DLTs (distributed ledger technology), a consortium of banks can establish a decentralized system that can be more efficient, less susceptible to attack, and serve as a new platform where innovative structures can be implemented to solve traditional challenges with privacy, speed, and cost.

But it's not decentralized. It's a DLT, it's a private blockchain and a private blockchain is by definition not decentralized.

I advise corpos on their infra and I'm tired of having the C-Level and VPs people mixing the decentralize concept with what is simply distributed.

Please change my mind.

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by pascalandy** [comment]
I'm looking at https://github.com/MicrosoftDocs/architecture-center/commits/master/docs/example-scenario/apps/decentralized-trust.md and nothing has changed regarding this issue.

I just want to understand your definition of decentralized. Thank you.

**Comment by doodlemania2** [comment]
Sorry about that - my original comments didn't carry over from our card. For this article, we are taking the position that decentralized concepts are applied here because there are multiple sources of the truth which can be independently verified and are tamper resistant. Your definition is more tightly constrained (which is great technically!) but we use the term in a broader sense to hold that a DLT spread among more than a single owner is sufficient for the concept to apply. Distributed, in our thinking, would mean there are multiple sources of truth, but there are no protections against tamper resistance (like a distributed DB). Hope that helps.

**Comment by pascalandy** [comment]
Thank you for clarifying. Have a nice day!
