### ISSUE TITLE
APIM and CDN integration

### ISSUE THREAD

**Issue by sfelaco** [MicrosoftDocs/architecture-center#2068]
Hi, please could clarify me about the relationship between APIM and CDN?
The diagram shows that the webapp connects to APIM and CDN. Are there two different endpoint?
For example site.com for the CDN static resources and api.site.com?
Could I a only FQDN, site.com, and create a CDN rules in order to redirect the API traffic to APIM?
Thanks so much. Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 524d1f97-ce37-f9ac-cf05-d33665eb34df
* Version Independent ID: fe4cc63f-a4b1-c30e-f39f-f4c3de1c57be
* Content: [Serverless web application - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/web-app#feedback)
* Content Source: [docs/reference-architectures/serverless/web-app.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/serverless/web-app.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#198078

**Comment by ckittel** [comment]
@sfelaco  - your analysis was spot on.  The user agent (browser) will be pulling static content (html, JS, CSS, etc) from one URL (say: www.example.com) while the javascript executing will be making XHR requests to a backend API at another URL (say: api.example.com).

If your APIs would benefit from a CDN in front of them, because they are all non-authenticated, HTTP GET requests and are highly cacheable, then you could indeed funnel those requests through the CDN and have those specific routes have an origin of your API Management service.

Typically APIs though are auth'd, are a mix of HTTP VERBS (most of which should not be cached), and do not typically get routed through a static content POP service as shown here.  Like CDN is designed for static content, ADNs are purpose built to provide a caching layer for dynamic content, but our out of scope for this specific article.  This article is using CDN for static content redistribution at global POPs, not for dynamic application (API) acceleration.

**Comment by sfelaco** [comment]
@ckittel thank you so much. Have a nice day!
