### ISSUE TITLE
How to send monitoring data from Azure Databricks to Azure Monitor using Python notebooks

### ISSUE THREAD

**Issue by crisansou** [MicrosoftDocs/architecture-center#2075]
Hello!

Do you have an example of how to send monitoring data from Azure Databricks to Azure Monitor using Python notebooks?

Best regards,
Cristina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f728cb2-b203-6b2f-4e3c-9d0e1be2516f
* Version Independent ID: 9ed58ead-f4d0-d9d0-01fe-82b11be235a7
* Content: [Send Azure Databricks application logs to Azure Monitor - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/databricks-monitoring/application-logs)
* Content Source: [docs/databricks-monitoring/application-logs.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/databricks-monitoring/application-logs.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#200054

**Comment by jocontr** [comment]
Hi @crisansou, even though we do not have a direct sample in python associated with this work, here is related information from Databricks and a sample Python project - https://docs.microsoft.com/en-us/azure/azure-databricks/quickstart-create-databricks-workspace-portal

Now, note that our work leverages the log4 family of technologies to create an additional appender in order to track a set of cluster metrics. Feel free to expand the current set to meet your needs.
