### ISSUE TITLE
Invalid template

### ISSUE THREAD

**Issue by josem0287** [MicrosoftDocs/architecture-center#2084]
Hello,
I'm receiving the following error when trying to deploy the template following the steps on this page:

{'additional_properties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template variable 'virtualMachineTemplate' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'

The issue seems to be the same as this one:
https://github.com/MicrosoftDocs/azure-docs/issues/8748

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74bb4b25-ebe2-264d-047d-3f651c52a9c5
* Version Independent ID: aed6ebef-6157-9608-3f85-0807c7fdf61d
* Content: [Implement a secure hybrid network - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/secure-vnet-dmz#feedback)
* Content Source: [docs/reference-architectures/dmz/secure-vnet-dmz.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/dmz/secure-vnet-dmz.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#204981

**Comment by absheik** [comment]
@josem0287 Please don't use AZBB.  The code base is in sustain and no further development is scheduled.  The npm package is a bit behind the source code available in GitHub.  If you build it yourself and run it it will work.  However for your purpose of cresting a DMZ in Azure I recommend using https://azure.microsoft.com/en-us/resources/templates/301-dmz-nsg/ 
![image](https://user-images.githubusercontent.com/16195413/79898634-6cc48780-83c0-11ea-8f9a-9b9387d1783d.png)
You can create a vnet DMZ like above

**Comment by ckittel** [comment]
@josem0287 - the issue you are experiencing appears to be coming from an upstream behavior change in `az deployment group create` (and the aliased `az group deployment create`).  As of a recent version it now appears to be downloading the `--template-uri` references and sending the downloaded template to the ARM `/validate` endpoint as if it was a local template instead of it being the remote template that it is.  `azbb` uses remote templates for its work.

There is a bug opened for this upstream in az cli to triage.  You can track it at Azure/azure-cli#12990
