### ISSUE TITLE
Is Azure Batch not a contender in this list?

### ISSUE THREAD

**Issue by MatchingRadar** [MicrosoftDocs/architecture-center#2216]
I have been looking into batch processing recently and stumbled across this article. I was wondering why it did not have any information on the Azure Batch service: https://azure.microsoft.com/en-gb/services/batch/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba35cbb-4160-0b5d-6829-103b25ad6ce9
* Version Independent ID: fa12ea8e-401a-9567-7b35-ffff532a99b6
* Content: [Choosing a batch processing technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/batch-processing)
* Content Source: [docs/data-guide/technology-choices/batch-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/batch-processing.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#249408

**Comment by ckittel** [comment]
Thanks for asking the question @MatchingRadar.  This article is under the "Databases" category, and isn't a general "batch computing" article.  As such, it's focusing on batch processors available in Azure that are custom built around the concept of batch database/data lake data processing, and offer affordances for the same.  While Azure Batch could be used to "batch process" data, it's not a "out of the box" recommendation for this general category of use cases.  If you have a use case that cannot be filled by one of the six options presented, you might not have a choice but to step back to a raw job and VM scheduler like Azure Batch (or any other custom "bring your own compute" system), but I wouldn't start any data journey with Azure Batch being the starting target unless you've already eliminated the others for some technical/practical reason.

Generally when customers think "Azure Batch" the types of workloads that come to mind would be video rendering, custom media transcoding, mass scale software test execution, etc.  Batch is a compute node manager/scheduler, and doesn't "optimize" for any specific type of workload, unlike the items mentioned in this article which do optimize for data.  Said another way, an article on rendering frames from applications like Maya or Blender, likely wouldn't suggest Azure Synapse as the compute engine.

I hope that helps.  I'll keep the issue open a bit longer in case you would like to carry the conversation further, but if you feel that was acceptable, you're welcome to close.  Thanks and have a great weekend!

**Comment by MatchingRadar** [comment]
Hey @ckittel, thanks for your response. 

I stumbled across the article whilst searching for a way to schedule a job to do some batch processing for files in blob storage. To summarise my situation, every night I would like to read from a container that has been populated by a Streaming Analytics job off of an Event Hub, do some extra categorisation and rejigging the formatting before placing them in Azure DakaLake (gen 2) storage as a conglomerate single file by groups. 

We currently do this via Azure Databricks using a Scala notebook script. I am aware of the rest api to Databricks and spent a bit of time getting it deployed via Azure Dev Ops (which was a little tricky even with the Databricks pipeline tasks) before I found some Azure Batch code in c#. 

I am a c# developer at heart and found it a lot easier to hook into the build pipelines to deploy things to Azure Batch. I also found that I could do all of the processing that Databricks/Scala/Spark is doing using c# and Azure Batch at a fraction of the cost. I realize there are many different ways to "skin a cat" (not sure where that phrase comes from) to accomplish ETL processes so would ask for your opinion on what you consider to be best - would you advise me not to use Azure Batch for my example? 

Out of interest what is the underlying infrastructure of Azure Batch built using (Azure Container Instances, Kubernetes, Docker, something else?) Will it exist in the long term or am I best switching to another methodology now?

**Comment by ckittel** [comment]
If your solution using Azure Batch achieves your business outcomes and contraints (whatever those may be for you: cost, SLO, maintability, observability, etc), then you're fine to use that.  Azure Batch is a general-purpose VM management & job scheduling platform that will do whatever you tell it to do :)  It's designed for highly-parrallel work, so if your job isn't parallel, it might not be a good fit.

Depending on the data size, you might even be able to do the same right from Azure Web Jobs or Azure Functions.  Guessing though you're dealing with a large amount of data that might not be suitable for one of those.

I would say that if you plan on doing more transformation or start combining data from more sources, and wish to have more of a "platform" approach to those, then gravitating toward a more data-centric tool might be good (like Databricks) since it "knows" the primitives a bit more and has a more robust pattern library and community.  You could even look to see if just Azure Data Factory would work for you as well.  That can be a very productive data pipeline buildout solution, low to no code; again, depending on your specifics.

I'm not sure what the Batch Service itself runs on under the hood, sorry.

Azure Batch does not have any announced end of life and is still receiveing new features.  We just launched [Private Link for Batch](https://azure.microsoft.com/en-us/updates/azure-private-link-for-azure-batch-is-now-generally-available-in-select-regions/) about a month ago and continue to add additional capabilities.

**Comment by ckittel** [comment]
At this point, we do not plan on updating this document with an Azure Batch recommendation, and will stick with data-centric services for this specific article.  Thank you for the conversation and question around this.  As such, I'm going to close the issue as is.  Have a great day.
