### ISSUE TITLE
Role issuance order when multiple roles are assigned to the same principal for a given app

### ISSUE THREAD

**Issue by boboldi** [MicrosoftDocs/architecture-center#2217]
Certain SAML service providers can only evaluate the first value from the Role claim, if it contains multiple values.
There are scenarios where the issuance order for the role values needs to be controlled, in case a user has multiple roles assigned to them.

Currently, neither assignment order nor the order in which the roles are defined in the app registration manifest do not influence the order or set a precedence to on how the roles should be issued.

This CAN be achieved by controlling the GUID value from the role.
Practical example:
generating a list of GUIDs and incrementing the value one by one, can control the order in which the roles get placed in the Role claim inside a SAML token, should multiple roles be assigned to the same user:

00000000-b5c0-4e2f-bd28-4c8e565e291f
00000001-b5c0-4e2f-bd28-4c8e565e291f
00000002-b5c0-4e2f-bd28-4c8e565e291f
00000003-b5c0-4e2f-bd28-4c8e565e291f

This behavior should be documented if it is consistent since it could address the above mentioned scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#249461

**Comment by ckittel** [comment]
Hey there @boboldi, that's unfortunate that the SAML consumer was programmed only to look at the first item in the `appRoles`  (`roles` in SAML) array.  Out of curiosity, what consumer of this token was written to only look at the first item in this array?  Any chance a bug (read: feature) could be opened up upstream to address that?

I don't see any documentation or internal implementation guarantees that implies that `appRoles` (`roles`) has a stable sort order; matter of fact we have at least one documentation example showing a non-alphabetical sort on `id`.  Taking a dependency on the order in which they return would be a high risk activity, that we'd advise against to ensure no hard-to-track down issues arise . For example, depending on how it's used, you could end up having all admins locked out of the system because of the order in which they return changed.

While I see where you're coming from, I hesitate to recommend a practice that there no evidence or documented guarantee that it won't change in the future. I might have missed the documentation on where we make this promise, so if you have evidence of this, other than "it works that way now" I'd love to dig in.  I just can't find that evidence.  If you have it, I'll follow through then with the Microsoft Identity Platform team to validate it will be stable.  Until then, it's best to assume it's an unstable ordering.

Maybe even better, you could alternatively ask this question right to the [Microsoft Identify Platform team on this page](https://docs.microsoft.com/azure/active-directory/develop/active-directory-enterprise-app-role-management) and they can give you an authoritative answer (which I cannot).  If you learn from them that it's, by contract, consistent, then we can include guidance to the same here, as you suggested.

**Comment by ckittel** [comment]
I'm going to go ahead and close this issue based on my recommendation to avoid taking a dependency on the order.  If however you do find evidence that order is stable and will remain stable, we can continue the conversation (you can reopen this or start a new issue) and consider how we should incorporate that guidance.  Thanks.
