### ISSUE TITLE
Centralized App secrets

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/architecture-center#2229]
The page states that for a key vault:

> To use these scenarios, the sign-in identity must [...] have explicit access policies for retrieving the secrets in Azure Key Vault.

I didn't test it yet, though I would expect the new (in preview) KeyVault roles?
Eg:
* Key Vault Crypto User : can perform cryptographic operations on keys and certificates.
* Key Vault Secrets User : can read secret contents.

![image](https://user-images.githubusercontent.com/1635825/87551854-36da2b00-c6b1-11ea-9365-765c8f88b411.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 336f0bcf-8699-ed68-82e6-e0b2ee103680
* Version Independent ID: eaa88128-433a-09eb-7ff8-0b65e3f6afb6
* Content: [Centralized app configuration and security - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/solution-ideas/articles/appconfig-key-vault)
* Content Source: [docs/solution-ideas/articles/appconfig-key-vault.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/solution-ideas/articles/appconfig-key-vault.md)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @sowmyans
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#267956

**Comment by ckittel** [comment]
Yup, I would expect the same as well.  If the application identity exists within an access policy or associated with an Azure RBAC role that grants secret list/read access, you should be good to go.  The client's HTTP request for this information is the same either way, this is a server-side resolution concern.

As with anything preview, ensure you are testing in a non-production environment.

I wouldn't go with a Built-in role more permissive than `Key Vault Reader (Preview)` though, since it doesn't need the access, at least from the Azure App Configuration service perspective, more than that -- and make sure that permission is scoped to just the resource(s) needed.

Thanks for reaching out @Styxxy.  Have a good day.
