### ISSUE TITLE
Secure the network flow - How will this work

### ISSUE THREAD

**Issue by melzayet** [MicrosoftDocs/architecture-center#2248]
In the secure network flow diagram, it depicts outside initiated traffic in green and cluster initiated traffic in orange: https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks#secure-the-network-flow

I don't see the green traffic request/response will work as in the diagram

The dotted green return traffic should go through Azure Firewall because of UDR setup. That's why AKS docs mentions the need for using inbound NAT on Az Firewall

Thanks,
Mahmoud

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46723a24-75ac-f6e2-c172-d3827ca0b7d6
* Version Independent ID: c975744e-e594-5667-14b3-c38824bbe24c
* Content: [Baseline architecture for an Azure Kubernetes Service (AKS) cluster - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks)
* Content Source: [docs/reference-architectures/containers/aks/secure-baseline-aks.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/secure-baseline-aks.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#271079

**Comment by ckittel** [comment]
Thank you for reaching out @melzayet.  The two traffic flows are from distinct origins.  The top (green if you can see the colors) flow is HTTP traffic destined for your cluster's workloads (the web app/api, etc) running on nodes in the cluster. the HTTP response for those requests will egress back out to the WAF and to the client.

The bottom (orange-ish) flow is traffic that originated in the subnet containing the nodes.  This would be traffic out to external container registries, the Kubernetes API server, etc.  Basically any cluster-originated traffic that we want to protect with our corporate egress firewall rules.

Because the traffic originated from outside of the UDR-ruled network and the fact we are using _internal_ load balancer in a separate subnet, it takes the same return path.  The UDR-rule applies to traffic originating within its scope.

Also, to be clear, this solution presented solves for **egress** lockdown (as defined as traffic originating from the cluster) only, it doesn't funnel both ingress and egress through the firewall.

I'm assuming the DNAT part you're talking about is coming [from this section](https://docs.microsoft.com/azure/aks/limit-egress-traffic#restrict-egress-traffic-using-azure-firewall) in the AKS docs ([specifically this](https://docs.microsoft.com/azure/aks/limit-egress-traffic#add-a-dnat-rule-to-azure-firewall)).  In that case, they are also forcing all ingress traffic to also flow through the firewall. In their case, they are using a _public_ load balancer for ingress, our solution does NOT use a public load balancer for ingress.  We are making contact with AAG, which is then routed through a _internal_ load balancer in an ingress subnet, which then will not be subject to the asymmetric routing issue.  If you exposed your services directly via the public load balancer IP, then you'd for sure run into the asymmetric routing issue.  [Here is the docs](https://docs.microsoft.com/azure/firewall/integrate-lb#internal-load-balancer) where we talk about Internal load balancers note being subject to this asymmetric routing issue.

Let me know if I can help clarify any more - I know this seems a bit "counter intuitive."  Feel free to deploy using the reference implementation, at the end of that journey you'll have a website where workload HTTP traffic is handled via the ingress route (Client -> WAF -> internal LB -> nodepool -> WAF -> Client) and cluster-originated traffic (nodepool -> FW -> external resource -> FW -> nodepool) is handled via the egress route.

**Comment by PramodValavala-MSFT** [comment]
@ckittel Thanks for sharing insights on this! I am assigning this issue to you.

**Comment by melzayet** [comment]
@ckittel thank you very much for the detailed and informative reply. I think my confusion came from the asymmetric issue but you clarified very well. Thanks again for taking the time
