### ISSUE TITLE
Terms and conditions disallow use of Azure icons in diagramming tools?

### ISSUE THREAD

**Issue by simonbrowndotje** [MicrosoftDocs/architecture-center#2251]
Hi, I'd like to publish an Azure theme for [Structurizr](https://structurizr.com) (a software architecture diagramming tool), but the (new?) terms and conditions seem to disallow this. Specifically (emphasis mine):

> The icons may not be used in advertising, in books and other printed matter, on clothing or other promotional items, __in online and Internet locations, in software applications__, in television programs, in commercials, in movies, or on video.

Structurizr themes are publicly accessible on the Internet, for example: https://structurizr.com/help/theme?url=https://raw.githubusercontent.com/structurizr/themes/master/microsoft-azure/theme.json 

The terms and conditions seem to imply that all diagramming tools that want to bundle the Azure icon set can no longer do so. Is this correct?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6624d44c-f9f6-02f8-2c67-0f0637fed62e
* Version Independent ID: 9346a8ff-bab5-be2c-9dc1-d546fda1efa9
* Content: [Azure Icons - Azure Architecture Center](https://docs.microsoft.com/en-gb/azure/architecture/icons/?WT.mc_id=docsmsft-twitter)
* Content Source: [docs/icons/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/icons/index.md)
* Service: **architecture-center**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#271838

**Comment by BhargaviAnnadevara-MSFT** [comment]
@simonbrowndotje Thanks for the question. Looping in @adamboeglin to provide inputs on this.

**Comment by simonbrowndotje** [comment]
I see that the terms and conditions have changed. Thank you, that's much appreciated. I've created a theme for Structurizr, which you can see at https://structurizr.com/help/theme?url=https://static.structurizr.com/themes/microsoft-azure-2020.07.13/theme.json

Structurizr users will use the styles in their architecture diagrams, and Structurizr doesn't permit icons to be cropped, flipped, rotated, distorted, or changed in any way. I think this theme is permitted by the new terms but if I'm mistaken, please do let me know, and I'll remove it.

**Comment by davidjgraph** [comment]
@simonbrowndotje If they are not in the license you don't break the license by not following them. You may just annoy someone so that the license is changed 8-)

My concern is around:

"...permits [licensee] to use these icons in architectural diagrams...about Azure to illustrate the specific function or relationship involving Azure services or products."

"You may copy, distribute, and display the icons only for the permitted use..."

So, if a user adds one of the icons to a diagram that isn't "about Azure" then they are in breach of the license. I understand the idea, i.e. use these for Azure diagams. When using them directly, whoever agrees to the license needs to follow it.

The problem comes for software that uses the icons to build diagrams/visualizations. We'd have to show users the license and ensure they agree and accept liablity.

Maybe the author of the new license could explain the problem they are trying to solve and we work out something that meets all needs?

**Comment by adamboeglin** [comment]
@davidjgraph, could you reach out to me via email?  adam.boeglin@microsoft.com

I'd love to discuss this (and better partnerships with diagrams.net) with you directly.  We absolutely want to make these icons available to those who need them wherever they create diagrams.

**Comment by adamboeglin** [comment]
We've updated the terms to remove the language requiring these icons be used in Azure diagrams.

@davidjgraph, let me know if this hasn't address all your concerns.

**Comment by adamboeglin** [comment]
We really appreciate all the feedback and engagement from the community on this!

**Comment by davidjgraph** [comment]
Perfect, thanks for your quick response.
