### ISSUE TITLE
Bounded Context

### ISSUE THREAD

**Issue by sheshmantha** [MicrosoftDocs/architecture-center#2259]
I think it is important to call out that an entity can represent itself differently to different Bounded Context.  For example, the entity Drone will expose different details for Drone Management than for Drone Booking.

The article tries to do that but the nuance of, "an entity representing itself differently for different contexts" is missed - hence suggesting that it be called out explicitly.  OR link to another page that exemplifies how same entity might appear in different contexts (e.g., Martin Fowler's version).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e55d3a73-7618-45ba-b281-bb70dd258842
* Version Independent ID: 7f5cd352-0998-a214-8dfc-c19898cecd21
* Content: [Domain analysis for microservices - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/microservices/model/domain-analysis)
* Content Source: [docs/microservices/model/domain-analysis.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/microservices/model/domain-analysis.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @adamboeglin
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#273359

**Comment by jocontr** [comment]
Thank you @sheshmantha , point taken. My team will make sure to add the note.

**Comment by RobBagby** [comment]
@sheshmantha - It seems to me that the following paragraph gets across the point that the same entity will have different features/attributes in different contexts:
_If we tried to create a single model for both of these subsystems, it would be unnecessarily complex. It would also become harder for the model to evolve over time, because any changes will need to satisfy multiple teams working on separate subsystems. Therefore, it's often better to design separate models that represent the same real-world entity (in this case, a drone) in two different contexts. Each model contains only the features and attributes that are relevant within its particular context._

I am going to close this issue. Please re-open if you do not think your issue was addressed.
