### ISSUE TITLE
Q: What are the considerations in choosing Traefik ingress controller

### ISSUE THREAD

**Issue by nitinkhandelwal26** [MicrosoftDocs/architecture-center#2261]
[Enter feedback here]
Can you please elaborate here in more details what is the design decision on choosing :
Use Traefik as the Kubernetes ingress controller.

Where we have other ingress controllers like AGIC, NGIX, and HAProxy, etc, Any special consideration or benefit in choosing Traefik here?
One more thing if we use AGIC then do we need to use App Gateway in front of that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80713a10-3600-b049-116e-db4c723f54e9
* Version Independent ID: 777a3dae-bcf3-6680-aaad-1c8a2fe98850
* Content: [Case study – Contoso Bicycle - Azure Architecture Center](https://docs.microsoft.com/en-in/azure/architecture/reference-architectures/containers/aks/case-study-contoso)
* Content Source: [docs/reference-architectures/containers/aks/case-study-contoso.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/containers/aks/case-study-contoso.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#275118

**Comment by ckittel** [comment]
Hey there @nitinkhandelwal26, thanks for the question.

Since kubernetes doesn't provide an ingress controller for you, this is one of many places where you have a choice on what to bring to satisfy your business needs.  You're right to call out the popular options such as you did.

Each option offers their own pros/cons.  In this reference architecture we wanted to show bringing an open source solution to the mix.  In this case, Traefik as it is a popular choice with our customers, it's well supported by the community, and solved for our desire to showcase pods getting secrets from Key Vault via the CSI KeyVault Driver.  While we could have taken a dependency on any of the ones you mentioned or others, Traefik is a great starting point for many customers coming to AKS.  Feature rich, offers great workload deployment strategies (Blue Green), wonderful secret (cert) affordances, etc. and can be tied to your workload and managed directly along side of it. (nothing preventing you form having an ingress controller per workload for maximum blast radius isolation)

AGIC or any other ingress controller may also suit your needs.

To answer your question about how AGIC works, you still need an external Application Gateway ([new](https://docs.microsoft.com/azure/application-gateway/tutorial-ingress-controller-add-on-new) or [existing](https://docs.microsoft.com/azure/application-gateway/tutorial-ingress-controller-add-on-existing)), only instead of routings being actualized in your ingress controller (like Traefik), they are actualized in Application Gateway.  The add-on interacts with your Application Gateway via imperative operations.  This does have impact on your ARM templates you use to do deployments, you don't want an infrastructure deployment to "remove" routes from AAG only for the ingress controller to have to "put them back" later... you'll experience outages -- so additional planning needs to happen around the management of that AAG resource, decoupling it from your infrastructure deployments a bit more.

Hope that helps you, if it does, you can close the issue (if we don't hear back in a while, we'll close the issue as well.)  Cheers, have a good day.
