### ISSUE TITLE
Guidance on managing code analysis that flags static usage pattern

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/architecture-center#2438]
This article describes a static usage pattern for HttpClient, which is an object that implements IDisposable.
This pattern will be flagged by Code Analysis because it doesn't call IDisposable::Dispose. 

This documentation should have a note about managing the code analysis rules that are creating flags for this recommended usage pattern, Many people attempting to follow best engineering practices set up their systems to require resolution of all code analysis diagnostics, because they trust code analysis to be accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dfc831d-af15-b8a9-5fc6-335bce4af155
* Version Independent ID: e2370017-a358-c817-2a69-0d036066f5bf
* Content: [Improper Instantiation antipattern - Performance antipatterns for cloud apps](https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/)
* Content Source: [docs/antipatterns/improper-instantiation/index.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/antipatterns/improper-instantiation/index.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#319841

**Comment by AnuragSharma-MSFT** [comment]
@Paul-Dempsey Thank you for the feedback. We are actively investigating and will get back to you soon.

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @Paul-Dempsey, sorry for the delay in my response, we have assigned this issue to the author to review further and take the next course of action.
@dragon119, sorry for the delay.

**Comment by BryanLa** [comment]
@Paul-Dempsey - apologies for the long delay on this issue, and thank you for raising this.

I was not able to repro the code analysis warning (which I'm assuming is the [CA2000](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2000) warning), when using HttpClient with a class-level static field (as illustrated in this pattern). Also, there seems to be a [general consensus](https://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed-between-requests/15708633#15708633) that this is the correct way to use HttpClient (as a shared/static object), and that Dispose() does not need to be called when used this way. 

I will close this issue for now, but please let us know if you feel otherwise or have a simple repro you can share.

#please-close
