### ISSUE TITLE
"Deploy on Azure" template for SAP production workloads using an Oracle Database on Azure not working

### ISSUE THREAD

**Issue by mimergel** [MicrosoftDocs/architecture-center#2450]
Hi,

the linked deployment on the documentation page 
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-production
doesn't work. The deployment leads to the following error: 

"message": "Bereitstellungsinhalt kann nicht von \"https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/sap-3-tier-marketplace-image-md//shared/loadbalancer.json\" heruntergeladen werden

Could the document owner please correct and reference to a working template?

Thanks,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e700b9a2-8b1d-5d55-95ec-1bb123d2586a
* Version Independent ID: 7f4b8f89-a777-b03b-e0af-d3d890745088
* Content: [SAP deployment on Azure using an Oracle DB - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/sap-production)
* Content Source: [docs/example-scenario/apps/sap-production.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/sap-production.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @DharmeshBhagat
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review.  This is a Microsoft Internal DevOps Bug ID AB#

**Comment by BryanLa** [comment]
@mimergel - apologies for the long delay on a response, and thanks for reporting this..

This is likely irrelevant for you now, but just for closure, the article has gone through several iterations since this issue was filed. I searched commit history and could not find any occurrences of the specific `loadbalancer.json` file you referenced. Also, it appears that the **Deployment** section has been removed, in favor of more specific guidance, and the following disclaimer: 

"*To deploy this reference architecture, you need the appropriate licensing of SAP products and other non-Microsoft technologies.*" 

Also FYI, I did find the current versions of the SAP quickstart templates [here](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/sap).

I hope this helps, and apologies again for such a long delay on this.

#please-close
