### ISSUE TITLE
Invalid MFA credentials

### ISSUE THREAD

**Issue by FMauroy** [MicrosoftDocs/architecture-center#2552]
Great doc, thank you very much!

But what can we do when the negotiation works properly between AAD and AWS (per the test feature in AAD SSO) but AWS replies with the following error?

![image](https://user-images.githubusercontent.com/1107417/102635250-5b9c6800-4153-11eb-8650-b11d8d6e3c63.png)

Is the issue in AWS (as I expect) or in AAD? Is there a way to get more info on this error?

Thanks a lot for any idea you might have.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b08461-26fb-d148-a749-9b61217af0f8
* Version Independent ID: 1329c651-e8f6-cc68-4205-739dfbbcef4f
* Content: [Azure AD security for Amazon Web Services (AWS) - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/aws/aws-azure-ad-security)
* Content Source: [docs/reference-architectures/aws/aws-azure-ad-security.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/aws/aws-azure-ad-security.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by femsulu** [comment]
@FMauroy Thanks for bringing this to our attention. We are actively investigating and will get back to you soon.

**Comment by shashishailaj** [comment]
@FMauroy The screen which you have mentioned is from AWS and seems that AWS is not allowing the access. I am assuming that you have followed the article to enable Azure AD based SSO for AWS access. In this case , I would first check whether the Azure AD sign in was completed properly or not . You can check the Azure AD signin logs using https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/troubleshoot-conditional-access because the MFA is implemented using Conditional access in this case. If you find that the user's signin did not complete successfully we would find the reason for the same in the logs. In case it was completed then , we would check why AWS is unable to consume the token . this can only be seen in the AWS activity logs. I do not have a test environment with AWS hence I may not be able to provide more insights on that . however if you still do not find the reason for the user who faces this, I would suggest to open a support case for this because there are multiple reasons why this could happen and a HTTP debug trace while accessing will provide more clarity on reasons why this is happening . 

Thank you.

**Comment by JayaChatterjee-MSFT** [comment]
@FMauroy Following up to understand whether you got a chance to review our previous comment.

**Comment by JayaChatterjee-MSFT** [comment]
@FMauroy Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly reopen the issue and continue the discussion.
