### ISSUE TITLE
Gateway looks like a orchestrator 

### ISSUE THREAD

**Issue by vtahlani** [MicrosoftDocs/architecture-center#2604]
[Enter feedback here]

Is gateway not doing job of orchestrator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 658a04f2-a906-dd3a-b4ce-3f2c7dcaad8f
* Version Independent ID: 974d5fdf-e7d8-fb51-4195-9d2dea89b6f4
* Content: [Gateway Aggregation pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/gateway-aggregation)
* Content Source: [docs/patterns/gateway-aggregation.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/gateway-aggregation.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by absheik** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/362676/>362676</a>

**Comment by Grace-MacJones-MSFT** [comment]
Thank you for your comment. As suggested by @absheik currently this is under review internally. We will update the status on this thread.

**Comment by PramodValavala-MSFT** [comment]
@vtahlani While it is similar, there is a fundamental difference as mentioned under considerations

> The gateway should not introduce service coupling across the backend services

Unlike an orchestrator, the gateway simply forwards requests (or sub-requests) to separate entities and these forwarded requests are not dependent on responses from other requests.

This is like how one can send a batch of messages to a message broker instead of making a call for each message, useful in constrained networks.

Another example would be HTTP/2 Server Push, which sends required assets of a web page without the client having to make requests for each.

**Comment by PramodValavala-MSFT** [comment]
@vtahlani Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@vtahlani Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
