### ISSUE TITLE
External sources and autoscaling capabilities of Azure Synapse

### ISSUE THREAD

**Issue by gorros** [MicrosoftDocs/architecture-center#2774]
I think Azure Synapse capabilities described the table in this article does not take into account these point
- Spark pools can have autoscaling enabled
- PolyBase enables you to retrieve data from many external sources and convert it into a tabular format

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba35cbb-4160-0b5d-6829-103b25ad6ce9
* Version Independent ID: fa12ea8e-401a-9567-7b35-ffff532a99b6
* Content: [Choosing a batch processing technology - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-guide/technology-choices/batch-processing)
* Content Source: [docs/data-guide/technology-choices/batch-processing.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-guide/technology-choices/batch-processing.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @ZoinerTejada
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/412505/>412505</a>

**Comment by v-fearam** [comment]
Hi @dineshspatelms

Sorry for the delay. 

The document has changed since the problem was reported.

Please take a look again. I would appreciate it if you could tell me what/where you would like to change and the link to support your suggestion. Even better, [open a PR](https://learn.microsoft.com/contribute/architecture-center/aac-contribute).


I'll close the ticket, but feel free to open a new one if you still have questions.
#please-close
