### ISSUE TITLE
DevOps for Azure Synapse Serverless Pool

### ISSUE THREAD

**Issue by dineshspatelms** [MicrosoftDocs/architecture-center#2796]
It would be great if you can add page for Synapse Serverless Pool DevOps.

Warm Regards,
Dinesh Patel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f10895e-4e1d-1cdd-2d57-32880e0cc45a
* Version Independent ID: 3518d0a5-ffd1-dfa7-6d6b-de2a9ef170d6
* Content: [Analytics end-to-end with Azure Synapse - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end?source=docs)
* Content Source: [docs/example-scenario/dataplate2e/data-platform-end-to-end.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/dataplate2e/data-platform-end-to-end.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @fabragaMS
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/418944/>418944</a>

**Comment by EdPrice-MSFT** [comment]
Thank you for the feedback!

**Comment by v-fearam** [comment]
Hi @dineshspatelms

Sorry for the delay. 


The document has changed a lot since the issue was reported. 

This issue was reported when the content looked like this: https://github.com/MicrosoftDocs/architecture-center/blob/33cea1a18c149866cc6abf3421493cd14635f968/docs/example-scenario/dataplate2e/data-platform-end-to-end-content.md


Now, there is in the document a link to https://learn.microsoft.com/training/modules/use-azure-synapse-serverless-sql-pools-for-transforming-data-lake/ in the [following section](https://learn.microsoft.com//azure/architecture/example-scenario/dataplate2e/data-platform-end-to-end?source=docs&tabs=portal#process-1)


I will close the ticket, but feel free to open a new one if you still have concerns.
#please-close
