### ISSUE TITLE
Knowledge mining software for product launch in a new market

### ISSUE THREAD

**Issue by brendawjy** [MicrosoftDocs/architecture-center#2913]
Hi there!

i would like to inquire if you have any suggestion for my needs. I'm a beer manufacturer and I'm going to enter a new country to distribute my product. can you suggest me any combination of knowledge mining softwares that i can use?

thanks!

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/453606/>453606</a>

**Comment by MonikaReddy-MSFT** [comment]
@brendawjy - - Thanks for bringing this to our attention.
I'm going to assign this to the content author so they can update the document accordingly.

**Comment by hallihan** [comment]
Since this is not reporting a specific problem with an article, I'll close this issue.  @brendawjy - take a look at the search results here: https://docs.microsoft.com/azure/architecture/browse/?terms=knowledge%20mining - there are several example scenarios that highlight knowledge mining.  You may also be interested in this article from August 2019: https://news.microsoft.com/transform/how-data-and-ai-are-helping-deschutes-brewery-respond-to-beer-trends-faster/
