### ISSUE TITLE
Precisions in alternatives section and Pricing section for API Management

### ISSUE THREAD

**Issue by IhorLeontiev** [MicrosoftDocs/architecture-center#2916]
Alternatives section 
No precision that  private connection scenario is only supported by Developer, Premium, and Isolated tiers of API Management

Pricing section
List of pricing tiers not full: there are no Consumption and Isolated tiers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55f4eba-7057-a500-a770-2e20d0dda242
* Version Independent ID: 6fb18f2d-1acb-76a9-70ad-11157f36bbc3
* Content: [Migrate a web app using Azure APIM - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/apim-api-scenario)
* Content Source: [docs/example-scenario/apps/apim-api-scenario.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/apps/apim-api-scenario.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @Begim
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/454692/>454692</a>

**Comment by AshokPeddakotla-MSFT** [comment]
@IhorLeontiev This has been taken care as mentioned above.

**Comment by v-fearam** [comment]
Hi @IhorLeontiev 


Sorry for the delay. 


The ticket was created some years ago, and the article has been updated several times since then.


Today in the cost section is a link to all the possibilities “API Management is offered in four tiers: developer, basic, standard, and premium. You can find detailed guidance on the difference in these tiers at the [Azure API Management pricing guidance here](https://azure.microsoft.com/pricing/details/api-management/).”


About the APIM flavor which supports some feature. There are links on the articles, and the information is on the related documents, for example:

* Alternative section, “For more information, see [Connecting APIM in internal mode to a VNet](https://learn.microsoft.com/azure/api-management/api-management-howto-integrate-internal-vnet-appgateway)”. In that link there is an “Availability” section: “This feature is available in the Premium and Developer tiers of API Management.”


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
