### ISSUE TITLE
Add scalability targets for Azure Files

### ISSUE THREAD

**Issue by spellinn** [MicrosoftDocs/architecture-center#2932]
Under "Azure limitations" you should mention the Azure Files limitation of 2000 file handles per share, which limits enterprise scalability when using Azure Files for FSLogix profiles as per the blueprint design.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Azure Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/458435/>458435</a>

**Comment by v-fearam** [comment]
Hi @[spellinn](https://github.com/spellinn),
Sorry for the delay. 


The ticket was created some time ago, and the article has been updated several times since then.


There is not an “Azure limitations” section any more.   I am not able in the current version see a reference to “Azure Files limitation of 2000 file handles per share”.
[I found same information that could be related to the subject](https://learn.microsoft.com/en-us/azure/storage/files/storage-files-scale-targets#file-scale-targets)
“Maximum concurrent handles per file, directory, and share root”, there is a limit of 2000 _concurrent handles_.
 
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
