### ISSUE TITLE
Modify how MCAS connects to AWS

### ISSUE THREAD

**Issue by richarddiver-ms** [MicrosoftDocs/architecture-center#2966]
Hi team, I am one of the original content authors for this document, it has recently come to light that some of the MCAS UI changes mean this document needs to be updated to reflect the new onboarding process for the AWS app to be managed via Session Controls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4cac8b6-d73b-07aa-dac0-2f833e0b95f9
* Version Independent ID: 29e460db-0e0a-265f-ff5e-e242cd24b165
* Content: [MCAS and Azure Sentinel for Amazon Web Services (AWS) - Azure Solution Ideas](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/aws/aws-azure-security-solutions)
* Content Source: [docs/reference-architectures/aws/aws-azure-security-solutions.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/reference-architectures/aws/aws-azure-security-solutions.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/463254/>463254</a>

**Comment by v-fearam** [comment]
Hi @richarddiver-ms,

Sorry for the delay.

The document has changed a lot since the issue was reported. 

This issue was reported when the content looked like this: https://github.com/MicrosoftDocs/architecture-center/blob/b41e5098bea0c1d08e3729a0913deb3543f8c80d/docs/reference-architectures/aws/aws-azure-security-solutions-content.md

Now, there is not MCAS reference as before.

I will close the ticket, but feel free to open a new one if you still have concerns.
#please-close
