### ISSUE TITLE
Unhelpful links

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/architecture-center#3089]
The September section contains links to "Updated" articles, when I click on them they open pages that we updated in March and April, this is not very helpful. What is the purpose of this section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd7bc22-da10-1d3b-ba22-7d5e374be441
* Version Independent ID: 9f466c91-adc7-0489-5b1e-17633d27c98c
* Content: [What's New in Azure Architecture Center - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/changelog)
* Content Source: [docs/changelog.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/changelog.md)
* Service: **architecture-center**
* GitHub Login: @doodlemania2
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/496783/>496783</a>

**Comment by ckittel** [comment]
@DeanGross -- Sometimes articles are updated but their "Last Modified" date is not changed.  That "Last Modified" date is the date that is shown on the frontmatter of the article.  If an item shows up in the changelog it's because it met a threshold of change (usually number of lines edited, as a percentage).  But sometimes those are just formatting updates and don't require the Last Modified date to be adjusted.  Last Modified usually means that the content was reviewed or changed in a significant way.

Sorry for any confusion this causes in the automated changelog feed.  I'm going to close as we do not have any plans on updating the logic for the changelog feed at this time, but I'll note this request to evaluate how we can be more clear about this.
