### ISSUE TITLE
out-of-date github repo and use of legacy Azure ML servies

### ISSUE THREAD

**Issue by ahmedbham** [MicrosoftDocs/architecture-center#3141]
The documentation is based on legacy Azure ML services, which is not recommended by Azure itself. It requires you to spin up Data Science VM, which is extremely expensive, and only available in very few regions. So, if you start the tutorial by creating workspace and storage in non-supported regions, then try to create the VM, it won't work. 

Also, many of the commands are obsolete and doesn't work. Additionally, the dataset location in Azure blob specified in this article is incorrect. There are many other issues, that I can't list all of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19033c57-ab48-2a4e-84f2-190808494260
* Version Independent ID: bac1e872-3906-f202-4a97-842a67c88706
* Content: [Build and deploy a model in a SQL Server VM - Team Data Science Process - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/data-science-process/sql-walkthrough)
* Content Source: [docs/data-science-process/sql-walkthrough.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/data-science-process/sql-walkthrough.md)
* Service: **machine-learning**
* Sub-service: **team-data-science-process**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/509749/>509749</a>

**Comment by marktab** [comment]
@ahmedbham  We are currently reviewing this page along with several others.  What is likely to happen is that we will remove them from this section of documentation since TDSP is focused on architectural advice.  This example was made by people long gone from active contribution.  Thanks for your feedback.  

@david-stanford  We may close this issue -- since I don't want to tie the larger effort (which is internal) to a ticket.  But I'm OK to mention on this public-facing portal that we know about the dated nature of some examples, and are working to resolve best messaging going forward.

**Comment by ram-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
