### ISSUE TITLE
Subnet overlap 

### ISSUE THREAD

**Issue by lakshmikanthKGit** [MicrosoftDocs/architecture-center#3155]
[Enter feedback here]

PLS Subnet and Bastion subnets are overlapping doesnt it a problem?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d19d00-c368-c49f-0b21-50004f05f2ef
* Version Independent ID: b0dd7137-6c32-84f5-d604-b6f9bca2768b
* Content: [Design a hybrid Domain Name System solution with Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/hybrid/hybrid-dns-infra)
* Content Source: [docs/hybrid/hybrid-dns-infra.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/hybrid/hybrid-dns-infra.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/514079/>514079</a>

**Comment by lakshmikanthKGit** [comment]
@EdPrice-MSFT : let me know if my understanding is wrong.

**Comment by v-fearam** [comment]
Hi @lakshmikanthKGit

Sorry for the delay. 

It is not a problem. It is by design.

It is part of a disconnected vnet, and in the article you could find the explanation “With this type of disconnected VNet, its IP addresses can clash with other IP addresses that are used in Azure and on-premises.”


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
