### ISSUE TITLE
Suggestion: Use Event Sourcing as configuration store

### ISSUE THREAD

**Issue by tianmiaohu** [MicrosoftDocs/architecture-center#3188]
Event sourcing could be the configuration store.  The applications can read the configuration from the materialized views and can be event consumers that listen to the configuration changes.  The benefits are:
1. Full history audit
2. Configuration recovery by going back to a snapshot or issuing compensating events
3. Separation of configuration update and configuration read for performance and resiliency

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a97c79-e300-9361-a398-558ae26378ce
* Version Independent ID: 30f222db-c119-69c7-f542-87e012890026
* Content: [External Configuration Store pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/external-configuration-store)
* Content Source: [docs/patterns/external-configuration-store.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/patterns/external-configuration-store.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @ckittel
* Microsoft Alias: **chkittel**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/524583/>524583</a>

**Comment by ckittel** [comment]
That would indeed be an interesting combination of two cloud design patterns, for the reasons you mentioned. Thanks for sharing your thoughts! This article is less focused on a specific, self-coded implementation; but if we ever decide to provide an example implementation, we'll consider including this as an implementation base.  Might be stuck though trying to balance complexity with instructional value though as well.

At this time, this article is not due for a refresh in the next six months+, so we'll make a note and close the issue (the bots would close it anyway due to it going dormant over the next couple of months).  Thanks again, have a great week!
