### ISSUE TITLE
qn-12-09-2021-issue-7

### ISSUE THREAD

**Issue by qkmnguyen** [MicrosoftDocs/architecture-center#3213]
qn-12-09-2021-issue-7

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/530540/>530540</a>

**Comment by AjayKumar-MSFT** [comment]
@qkmnguyen, Thanks for leveraging Azure docs feedback channel to raise this question. Since you have closed the thread I presume the issue is resolved, if it's not the case or you need further assistance kindly just let us know. 
-Please do share more details about your scenario/ask. 

-As a side note, this channel is reserved for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.
