### ISSUE TITLE
HTTP 202, wrong description

### ISSUE THREAD

**Issue by morten-nielsen** [MicrosoftDocs/architecture-center#3256]
There seems a small bug in the description of the sequence diagram

`For every successful call to the status endpoint, it returns HTTP 202.`

Should be 
`For every successful call to the status endpoint, it returns HTTP 200.`

The mention of HTTP 202, continues in other text blocks as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fea460c-4fac-723f-8df4-9d0811855a68
* Version Independent ID: 4be364ca-aee7-7b49-13e1-3a94408ed7b9
* Content: [Asynchronous Request-Reply Pattern - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/patterns/async-request-reply)
* Content Source: [docs/patterns/async-request-reply.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/async-request-reply.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @WillEastbury
* Microsoft Alias: **wieastbu**

**Comment by shashishailaj** [comment]
@morten-nielsen Thank you for your feedback . We will check this with the content team and update on the same.

**Comment by PramodValavala-MSFT** [comment]
@morten-nielsen Actually, I believe the `202` is the correct response here. The sequence diagram is in the wrong here.

While the backend processing is in progress, a `202` is what is expected since it signals the client to keep polling. When processing is complete, one of the following behaviors could be implemented

- Return a `200` response with the required response
- Return a `202` with a location header pointing to an endpoint that will return the required response
- Return a `302` redirecting the client to the endpoint that will return the required response

Hope that clears things up. We are assigning this issue to the content author to update the sequence diagram and any of the descriptions as required.

**Comment by morten-nielsen** [comment]
You are right @PramodValavala-MSFT it looks like 202 can be used like that, here is part of the description from ietf.

_The representation sent with this response ought to describe the request's current status and point to (or embed) a status monitor that can provide the user with an estimate of when the request will be fulfilled._

**Comment by WillEastbury** [comment]
The response from the original resource should return a 202, and point to a status resource.

When polled the status resource should return a 200 OK, as the resource being polled represents the status resource. Hence the diagram should be updated.

The text was updated recently in a customer-led PR, but the diagram was not.

Sent from Outlook<http://aka.ms/weboutlook>

**Comment by hallihan** [comment]
This issue duplicates #3396, we're working on an update under that issue. #please-close
