### ISSUE TITLE
AVD component relationships are not clear

### ISSUE THREAD

**Issue by MWL88** [MicrosoftDocs/architecture-center#3295]
I would like some clarification regarding the table listing the [Azure Virtual Desktop limitations](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop#azure-virtual-desktop-limitations). This table is also presented on the [Subscription and service limits](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#azure-virtual-desktop-service-limits) page.

Please clarify the following points:
- The tables lists various AVD objects and their parent container. The relationships described in the table are different to the relationships show in the diagram in the section describing [relationships between logical components](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop#relationships-between-key-logical-components) with description in the additional notes. Specifically, please clarify the relationship between the Host Pool, Application Group and Workspace objects. The table states the hierarchy is Workspace -> Host Pool -> Application Group, while the diagram shows (with notes) the hierarchy is Workspace -> Application Group -> Host Pool.
- Are the numbers stated in the `Service Limit` column the number of specific AVD objects that can be created per parent instance? e.g. the limit of RemoteApp instances is 500 per Application Group, so if I have 600 RemoteApp instances I must use at least 2 Application Group instances where each Application Group has no more than 500 RemoteApp instances.

Also, note (2) for the [diagram](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop#relationships-between-key-logical-components) states `Application groups assigned to the same host pool must be members of the same workspace`. Based on my experience deploying AVD components via ARM templates, note (2) is not correct, at least for API version `2021-07-12`, where I can deploy a single Host Pool, 2 Application Groups (both associated with the Host Pool) and 2 Workspaces with each associated with one of the Application Groups. Is this a _legacy_ limitation where Host Pools cannot be shared between Workspaces?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26be54d-0f67-5098-7839-98f5bb064188
* Version Independent ID: 187fa3ce-ade9-1b07-2af3-c874ec3d0aac
* Content: [Azure Virtual Desktop for the enterprise - Azure Example Scenarios](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/windows-virtual-desktop.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @TomHickling
* Microsoft Alias: **thhickli**

**Comment by TomHickling** [comment]
Both of these are correct because they are explaining something slightly different. In terms of the Limits document this is showing the actual limits per object based upon its parent object where the limitation applies. e.g., you could have 400 Host Pools per Workspace, if you wanted 500 you need a second Workspace. Whereas the "relationships" doc is showing the logical hierarchy that an Admin needs to know about when configuring all of the AVD objects for their users, i.e., Apps reside in AppGroups which reside in a host pool. Session hosts are also members of host pools and Workspaces contain only App Groups.
On note 2 yes this is now enforced. It’s not possible to add an appgroup to a workspace and then add a second app group from the same host pool to a second workspace, when an existing app group from the same host pool is already assigned to another workspace. I don't know when this limitation was implemented but would have expected it to be before that API version you mention. Thanks for raising I will get this looked at.

**Comment by MWL88** [comment]
Thank you for the clarification regarding the service limits and the AVD object hierarchy.

I was recently able to successfully deploy, via an ARM template, a Host Pool shared between multiple Workspaces.

I can confirm the ARM template now fails to deploy the second Workspace if the Workspace attempts to be associated with a Host Pool that is already assigned to another Workspace.

**Comment by v-fearam** [comment]
Your first questions were already addressed. 
From these details, I can't say why your deploy is failing. I recommend leveraging the support options available in the Azure portal if you are still facing this issue.
#please-close
