### ISSUE TITLE
Routing Traffic Diagram Fix

### ISSUE THREAD

**Issue by dimmand** [MicrosoftDocs/architecture-center#3316]
[Enter feedback here]
in the traffic routing sections based on the documentation the API management will contact the closest region to respond more quickly. In the diagram in the routing traffic section, the first West US 2 and second East Us API Management direct the request to the same stamp East US. However, the first API management West US 2 should direct the request to the stamp West US 2 respectively not to East US as the diagram shows.
![image](https://user-images.githubusercontent.com/34609431/155165206-d64b2cf3-3bf9-427d-9527-6a2ab7428df7.png)

https://docs.microsoft.com/en-us/azure/architecture/patterns/deployment-stamp#traffic-routing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6e8b74-b3e5-8acd-f517-39d5137cffc4
* Version Independent ID: e1d6ffde-14d9-8502-2ff2-7a8399de86dc
* Content: [Deployment Stamps pattern - Cloud Design Patterns](https://docs.microsoft.com/en-us/azure/architecture/patterns/deployment-stamp)
* Content Source: [docs/patterns/deployment-stamp.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/deployment-stamp.md)
* Service: **architecture-center**
* Sub-service: **design-pattern**
* GitHub Login: @johndowns
* Microsoft Alias: **pnp**

**Comment by johndowns** [comment]
@dimmand Thanks for your feedback.

The diagram is intended to show that, regardless of where the request comes from in the world (and whichever API Management instance it lands on), the request will be routed to the stamp for that tenant. So the lines connecting the API Management instances to the stamps don't necessarily match their regions.

For example, imagine a tenant normally resides in New York, and so their data is stored in the East US stamp. But they travel to California and then access the system. Their connection will go through the West US 2 region (because that's closest to where they are geographically when they make the request), but the request has to ultimately be served by stamp 3 (because that's where their data is stored).

I don't think the page clearly explains this at the moment, so I'll make some tweaks to make it clearer. I also noticed that the Cosmos DB components' regions aren't correct in the diagram, so I'll fix this at the same time.

Thanks again.

#please-close
