### ISSUE TITLE
The script for Defender is incorrect

### ISSUE THREAD

**Issue by brbish** [MicrosoftDocs/architecture-center#3317]
It has hard coded the value \share\. That value should probably be a variable or at least have <> brackets around it to let people know they need to change it.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by MayankBargali-MSFT** [comment]
@brbish Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-fearam** [comment]
Hi @brbish,


Sorry for the delay.


In the [Defender script](https://learn.microsoft.com/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#add-exclusions-for-microsoft-defender-for-cloud-by-using-powershell), I can see the \share as a variable.


```

 $ShareName = "share"             # Storage Account's file share name(line 4)

```


I think it has changed since you created the ticket. 


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
