### ISSUE TITLE
Custom Entity Recognition and Decision support alerts

### ISSUE THREAD

**Issue by sasi-patha** [MicrosoftDocs/architecture-center#3546]
Requirements put forth by business analysts / teams:
1. Extract fields like Title, Parties, Effective Date, Start Date, End Date, Duration, Total Cost, Signatories - which i think could be achieved with combination of Form Recognizer & custom entity extraction.
2. Analyze the extracted  fields , relationships, dependencies between master service agreements, amendment contracts. And finally alert on approaching actions or milestones.
3. Do all these over 50+ document templates, in other words , accross different clients as well as possibly multiple templates for each client.

I'm working to achieve this with Azure products and any plug-ins.
Last time i tried to do this with my own Search engine system, it seemed out of the capability of a search engine architecture
to solve this.
please suggest.

Thank you.
Sasi Kiran P.

**Comment by mike-urnun-msft** [comment]
Hello @sasi-patha - Thank you for your feedback. Since this channel is more for driving improvements towards MS Docs, could you make a new post for your question on [MS Q&A channel](https://docs.microsoft.com/en-us/answers/index.html) instead? That way, we’re able to make sure your questions are answered by the right product team & SMEs.

We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
