### ISSUE TITLE
`Terraform` should not be stated explicitly 

### ISSUE THREAD

**Issue by m-soltani** [MicrosoftDocs/architecture-center#3575]
Hey Team,
my feedback relates to the chapter `Key design strategies` -> `Reliable and repeatable deployments`: 

I find this pretty awful stating `Terraform` as Infrastructure as Code Technology for a "reference" as if other technologies like
 `ARM-Templates` or `Bicep` can't achieve the same :). One should concentrate more on the concept itself and less about `IaC` tool set.

Bests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ca3ab2-be89-6350-5035-2f96a3f50e23
* Version Independent ID: 73ca3ab2-be89-6350-5035-2f96a3f50e23
* Content: [Mission-critical baseline architecture on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-mission-critical/mission-critical-intro)
* Content Source: [docs/reference-architectures/containers/aks-mission-critical/mission-critical-intro.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-mission-critical/mission-critical-intro.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @CalCof
* Microsoft Alias: **prwilk**

**Comment by Grace-MacJones-MSFT** [comment]
Thank you for your feedback! We have assigned this issue to the author to review further and take the next course of action.

**Comment by CalCof** [comment]
Thanks for sharing this feedback and your opinion. 

This reference does not assert or imply that first-party technologies cannot be used to accomplish the same outcome, it merely makes a specific technology selection. I will, however, inject some additional language clarification to prevent any further confusion that the same cannot be accomplished with first-party technologies.

The goal of this architecture is to provide a prescriptive reference that is underpinned by production-grade implementation artefacts, which cannot be accomplished at an abstract "concept" level.

For transparency, the project principal of "grounded on customer truth" is what led to this particular design decision, since the majority of pilot customers (~70) which informed and validated this reference pattern leveraged Terraform. Azure is an open platform and does not discriminate between the use of first party (ARM templates, BICEP) or third-party technologies. Terraform is ultimately a dominant and popular IaC technology across major cloud providers, offering the required capabilities for this scenario. 

Also, for reference, the open-source GitHub artefacts also possess an ARM implementation of the zero-downtime deployment process.

**Comment by m-soltani** [comment]
Thanks for the clarification. Either of these two helps more: 
* Stating that this "reference" implementation used by many customers which preferred _Terraform_ as the IaC toolset. This avoids any possible misunderstandings for readers.
* As you've said, additional language clarifications that this "reference" implementation uses _Terraform_ but is not limited to it.

**Comment by ckittel** [comment]
@CalCof -- do you (or someone on your team) plan on getting the PR opened for this, or has this hit the backlog for a content dev in C+E Skilling?

**Comment by v-fearam** [comment]
It was already resolved at https://github.com/MicrosoftDocs/architecture-center/commit/ca149a20712cf7e33b597f4f61031fe1f79e8658

#please-close
