### ISSUE TITLE
subnet for VPN gateway

### ISSUE THREAD

**Issue by JakubProchazka** [MicrosoftDocs/architecture-center#3615]
New recommendation for GatewaySubnet is address range of /26 instead /27. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104eba32-c77e-b013-e161-ff616d16a0f7
* Version Independent ID: 3bc27d0a-ef32-f5f6-4c85-fe8e2e45155e
* Content: [Hub-spoke network topology in Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli)
* Content Source: [docs/reference-architectures/hybrid-networking/hub-spoke.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/hybrid-networking/hub-spoke.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by YashikaTyagi-MSFT** [comment]
@JakubProchazka 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by ckittel** [comment]
Hey there @JakubProchazka.  Our guidance for _GatewaySubnet_ is currently following the guidance of the ER/VPN Gateway docs at https://docs.microsoft.com/azure/vpn-gateway/vpn-gateway-about-vpn-gateway-settings#gwsub, which lists a recommended range of `/27` or larger.  Do you have a link that talks about the `/26` recommendation you mentioned so that we can cross-check?

**Comment by JakubProchazka** [comment]
Hey there @ckittel
I probably mistaken it with bastion subnet, where the new recommendation apply. I am sorry.
