### ISSUE TITLE
SAP Router - SNC example

### ISSUE THREAD

**Issue by Darryl-G** [MicrosoftDocs/architecture-center#3623]
Hello,

The SAP Router architecture example is specific to the use of SNC.
There is another scenario that does not seem to be well covered, using an IPSEC VPN.
SAP require 2x fixed public IP addresses (one for the VPN and one for the SAP Router VM).

Is it possible you can provide some architecture examples using IPSEC VPN for the SAP Router connection?

Thanks

Darryl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf95a78-b354-11c7-de36-2bc0787c930c
* Version Independent ID: fdf95a78-b354-11c7-de36-2bc0787c930c
* Content: [Inbound and outbound internet connections for SAP on Azure - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/guide/sap/sap-internet-inbound-outbound)
* Content Source: [docs/guide/sap/sap-internet-inbound-outbound.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/sap/sap-internet-inbound-outbound.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @msftrobiro
* Microsoft Alias: **robiro**

**Comment by msftrobiro** [comment]
Hello Darryl,

You are right, only the SNC way is described. I have added a brief clarification about this and not covering IPSEC in this document, in PR [3625](https://github.com/MicrosoftDocs/architecture-center/pull/3625).

Until now, in the Azure space I nor colleagues I know of, have come up with the request to use IPSEC SAProuter.
Other than working on network layer 3 instead of 7 (SNC) and using an open protocol and not proprietary SNC, I personally can't find any benefit of the more complicated architecture.
If you'd know of such customer requirement and need in Azure, attempting to implement it, feel free to contact me direct through email robiro on microsoft.com. 

best regards,
Robert

**Comment by Darryl-G** [comment]
Thanks Robert.
I'll be sending you an email in the morning. 😉

All the best


Darryl

**Comment by janewar** [comment]
how saprouter http connection

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 37568 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
