### ISSUE TITLE
Pricing Estimate link does not work

### ISSUE THREAD

**Issue by Miteshc1** [MicrosoftDocs/architecture-center#3665]
The pricing sample does not load

Looks like link to estimate no longer works.
https://azure.microsoft.com/en-us/pricing/calculator/?shared-estimate=b798fb70c53e4dd19fdeacea4db78276

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e4f4c7c-f268-b75b-2486-5c4418e5b24e
* Version Independent ID: 5d28faa1-20bc-1727-05ab-0b18eba1ba7c
* Content: [Data warehousing and analytics - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/data/data-warehouse)
* Content Source: [docs/example-scenario/data/data-warehouse.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/data/data-warehouse.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @alexbuckgit
* Microsoft Alias: **Alex.Buck**

**Comment by SaibabaBalapur-MSFT** [comment]
@Miteshc1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
@Miteshc1
After login I was able to see the estimation today.
![image](https://user-images.githubusercontent.com/62260324/226716267-297fa685-1d45-4629-9b4b-e1e3f0d00501.png)

And I observe not answer since many months ago. 
I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
