### ISSUE TITLE
wordiness

### ISSUE THREAD

**Issue by zissbilloutlook** [MicrosoftDocs/architecture-center#3734]
"Adding the extra layer to the application to implement the gatekeeper pattern will likely impact performance due to the additional processing and network communication required."

No.

This additional Gatekeeper layer between the client and protected service will diminish performance.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 428e4625-191f-a050-ec58-60fd2dddff86
* Version Independent ID: 3a4e385e-5761-3633-1ddf-46e1878b420d
* Content: [Gatekeeper pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/gatekeeper)
* Content Source: [docs/patterns/gatekeeper.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/gatekeeper.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by YashikaTyagi-MSFT** [comment]
@zissbilloutlook 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
Hi  @zissbilloutlook 


Sorry for the delay. 


“Adding the extra layer to the application to implement the gatekeeper pattern will likely impact performance due to the additional processing and network communication required.”


‘Impact’ does not mean ‘improve’. The sentence's spirit is ‘diminish performance’, a negative impact.


I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
