### ISSUE TITLE
Application Gateway hub/spoke

### ISSUE THREAD

**Issue by vunvulear** [MicrosoftDocs/architecture-center#3774]
What is the motivation for having the App Gateway in the Spoke and not in the Hub? Shouldn't we have all traffic direct to Hub and from there to the Spoke?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c9cfb32-2013-f31e-0209-d5194afc8d9e
* Version Independent ID: 9cabc767-9799-abcd-6ccd-11f164c30877
* Content: [Architecture of an AKS regulated cluster for PCI-DSS 3.2.1 - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets)
* Content Source: [docs/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-pci/aks-pci-ra-code-assets.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @PageWriter-MSFT
* Microsoft Alias: **prwilk**

**Comment by Naveenommi-MSFT** [comment]
@vunvulear 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
Hi  @vunvulear 

There are many topologies possible when using [Firewall and Application Gateway for virtual networks](https://learn.microsoft.com/azure/architecture/example-scenario/gateway/firewall-application-gateway).


In the current case, the selection was [Firewall and Application Gateway in parallel](https://learn.microsoft.com/azure/architecture/example-scenario/gateway/firewall-application-gateway#firewall-and-application-gateway-in-parallel). Because of its simplicity and flexibility, running Application Gateway and Azure Firewall in parallel is often the best scenario. Implement this design if there's a mix of web and non-web workloads in the virtual network. Azure WAF in Azure Application Gateway protects inbound traffic to the web workloads, and the Azure Firewall inspects inbound traffic for the other applications. The Azure Firewall will cover outbound flows from both workload types.


In this scenario, the decision was related to team responsibilities. The networking team is responsible for Hub and the workload team is responsible for spoke. The Application Gateway protects inbound traffic to the web workloads in this scenario and is coupled with the workload, not as a shared infrastructure component.  Generally speaking, in regulated environments, the more infrastructure control the workload team can be directly responsible for will give that team maximum affordances for security controls.  A hub is shared across multiple workloads, and minimizing the footprint on shared infrastructure, to a reasonable limit, was a goal.


It is not the case for this reference implementation, but it is worth to mention that the [Application Gateway could act as Ingress controller](https://learn.microsoft.com/azure/application-gateway/ingress-controller-overview) for AKS, which in that case you'd often expect to see a 1:1 with the cluster.

I will close the ticket, but feel free to re-open if additional clarification is needed.

**Comment by v-fearam** [comment]
#please-close
