### ISSUE TITLE
Message for Keith Hill

### ISSUE THREAD

**Issue by ridelane** [MicrosoftDocs/architecture-center#3796]
Hello Keith - I am trying to reach someone in the Azure percept and live analytics team. SiMa.ai is interested in exploring opportunities to participate in the certified hardware ecosystem. I did send a note to Moe Tanabian but haven't heard back. Perhaps his email box is quite full or he is in a different role? Would you be open to a brief conversation with us. We are an ML SoC (system on chip) inference accelerator that integrates several vital computer vision functions onto a single chip to achieve massive benefits over the Nvidia Jetson products. We are based in San Jose. How could we connect. My email is richie.singh@sima.ai and my phone is 425 922 4041.

Sincerely,

Richie Singh 
richie.singh@sima.ai
425 922 4041

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2336821a-c08d-ecfa-452c-249ee243bd1a
* Version Independent ID: 1b81e61e-6879-aadb-ac48-66090550fa74
* Content: [Computer vision with Azure IoT Edge - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/iot-edge-vision/#feedback)
* Content Source: [docs/guide/iot-edge-vision/index.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/iot-edge-vision/index.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @MSKeith
* Microsoft Alias: **keith**

**Comment by mike-urnun-msft** [comment]
Hello @ridelane - Thanks for reaching out and sharing this feedback. Since this repo is more for driving improvements toward our documentation for the Azure Architecture center, the issues opened here won't have an escalation path that would lead to a direct connection with the product group folks. Instead, please consider making a new post on [the MS Q&A channel](https://learn.microsoft.com/en-us/answers/index.html) and using the appropriate product tag, and one of our support engineers who work closely with that product group will review your feedback and make determinations on the best way for creating the communication path.

Since we didn't determine any changes to this documentation upon reviewing this feedback, we will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
