### ISSUE TITLE
Front door rewrites the HttpContext.Current.Request.Url arbitrarily 

### ISSUE THREAD

**Issue by fernandofilevine** [MicrosoftDocs/architecture-center#3797]
We have two separate App Services that receive traffic from a Front Door. One app service has a *.domain.net wildcard custom domain attached, and the other app service has a specific standalone-host.domain.net custom domain attached. 

When traffic is served to the wildcard app service, the HttpContext.Current.Request.Url header in .NET returns some specifichost.domain.net.

When traffic is served to the app with the specific host attached, the HttpContext.Current.Request.Url header in .NET returns standalone-host.azurewebsites.net instead of the expected custom domain: standalone-host.domain.net.

We understand the that workaround for this is to use the X-Forwarded-Host header when parsing Front Door traffic. 

However, the [Microsoft documentation](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/domain-names#name-resolution) states that we _should_ have been seeing the correct hosts resolved via HttpContext.Current.Request.Url.

Is this a bug, or an inaccuracy in the documentation? From our end, it seems like Front Door is arbitrarily choosing which domain name attached to an instance to use when rewriting the Request URI. 

How does Front Door determine which custom domain for an app service to write to the HttpContext.Current.Request.Url header? We want to understand why one app service returned the custom *.domain.net and the other returned the standalone-host.azurewebsites.net internal URI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67bda49f-42de-b78f-7f8c-593d343739e8
* Version Independent ID: 0f62d6f3-64fd-472a-32c9-0bb3dc583e86
* Content: [Considerations when using domain names in a multitenant solution - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/domain-names#host-header-resolution)
* Content Source: [docs/guide/multitenant/considerations/domain-names.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/considerations/domain-names.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @EdPrice-MSFT
* Microsoft Alias: **architectures**

**Comment by Naveenommi-MSFT** [comment]
@fernandofilevine 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by fernandofilevine** [comment]
One addendum: Both instances are running the same code

**Comment by v-fearam** [comment]
Hi @fernandofilevine

Sorry for the delay. 


This channel is intended for ‘Azure docs’ feedback- for sharing doc feedback and suggesting content improvements.


I'm not sure what is going on in your environment. 

The document [Azure Front Door Custom Domain]( [https://learn.microsoft.com/azure/frontdoor/front-door-custom-domain](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Ffrontdoor%2Ffront-door-custom-domain&data=05%7C01%7Cv-farambarri%40microsoft.com%7Ce0faa5f662fe4b0b988608db682a0471%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638218301896699024%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bu5SHdGpKRvGZNqKMUYpCBsA6j3Jcff70Q7qlHjaR%2F0%3D&reserved=0)) might help.


I recommend leveraging the support options available in the Azure portal if you are still facing this issue.


I will close the ticket.
#please-close

**Comment by ckittel** [comment]
@johndowns / @PlagueHO - do either of you have a perspective to share?

**Comment by johndowns** [comment]
Hi @fernandofilevine, I see this is a fairly old question so I'm not sure if it's still valid. I'll give a few thoughts just in case.

Firstly - the `X-Forwarded-Host` header should be propagated correctly by Front Door. For your scenario I would definitely be looking at that instead of `Host`, because Front Door can rewrite the `Host` header on requests quite legitimately. My first suggestion would be to log the raw request that your application receives to confirm that the `X-Forwarded-Host` header is correctly populated. If it's not, I'd open a support case for Front Door. If it is populated correctly, Front Door is behaving correctly.

Secondly - I don't know what logic ASP.NET uses for populating the `HttpContext.Current.Request.Url` property. The [documentation you linked](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/considerations/domain-names#name-resolution) doesn't mention the property at all, and this would be a question for ASP.NET rather than anything on the Front Door side. Front Door doesn't have any involvement in populating that property - that's up to the server you're using (in your case, ASP.NET). You might need to open a support case with ASP.NET to verify how this is supposed to work.

Thirdly - if you use Front Door rule sets, be careful to check that they aren't doing anything to modify the request before it goes to your application server, because this might be confusing matters too.

Hope this helps.

cc @ckittel
