### ISSUE TITLE
What about user integrity

### ISSUE THREAD

**Issue by wUEZRs** [MicrosoftDocs/architecture-center#3889]
I see a lot of the Zero Trust visios in the Microsoft library but I wonder about users and auth?

"verifies the trustworthiness of network packets that flow to applications"
- What about the user login?
With App Proxy and B2B, one could invite the client's guest users to log on to the App Proxy to shield the public front from 8 billion users and 8 billion bots

Why is that (pre-auth) not taken into consideration in modern ZT scetches?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f623b3a-09d7-d793-b007-85b59727c1df
* Version Independent ID: ec0506cd-cdba-784c-6832-ea59697dd39c
* Content: [Zero-trust network for web applications with Azure Firewall and Application Gateway - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/gateway/application-gateway-before-azure-firewall)
* Content Source: [docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/gateway/application-gateway-before-azure-firewall.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @erjosito
* Microsoft Alias: **jomore**

**Comment by erjosito** [comment]
I created https://github.com/MicrosoftDocs/architecture-center-pr/pull/9527 to explain that this article only refers to part of the zero-trust architecture (encryption and inspection), and authentication is out of scope.

**Comment by wUEZRs** [comment]
It would be good for us to also have some authentication architecture concepts in the ZT drawings

**Comment by JKirsch1** [comment]
I'm not sure why this issue was assigned to me because I only did a few formatting and language edits on [Zero-trust network for web applications with Azure Firewall and Application Gateway](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/gateway/application-gateway-before-azure-firewall).

But I'm closing this issue because the author set up [PR 9527](https://github.com/MicrosoftDocs/architecture-center-pr/pull/9527) to explain that the article focuses on inspection and encryption, and that authentication is out of its scope. That PR has merged, and the updated version is live.
