### ISSUE TITLE
Required more explaination

### ISSUE THREAD

**Issue by Arjun-Mandavkar** [MicrosoftDocs/architecture-center#4005]
There is sentence in the blog, 
"Collaborative domains where many users access the same data in parallel. CQRS allows you to define commands with enough granularity to minimize merge conflicts at the domain level, and conflicts that do arise can be merged by the command"
I cannot imagine the scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ec92e-c237-f3a6-1835-f2078486dcb3
* Version Independent ID: f597c9a2-f18f-3722-57f9-acd535472b0b
* Content: [CQRS pattern - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/patterns/cqrs)
* Content Source: [docs/patterns/cqrs.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/patterns/cqrs.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Arjun-Mandavkar

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
Hi @Arjun-Mandavkar 

Sorry for the delay. 


The sentence is related to: [“Commands should be task-based, rather than data centric. ("Book hotel room", not "set ReservationStatus to Reserved").

”](https://learn.microsoft.com/en-us/azure/architecture/patterns/cqrs#solution).


The pattern creates a sequence of tasks which are going to impact the write store. The size of what is going to do depends on the domain. For example: Sell the car XXX to John Doe. The granularity in your domain can be a tool to minimize conflicts, and we could manage the result. Selling a car implies several data collections, and the car selling is in parallel. We could design to be represented by one task and solve the way to sell only once “car XXX” there.


The problems need to be solved with or without CQRS, but here you have the concept of commands queue. 


I will close the ticket, but feel free to open a new one if you still have concerns.
#please-close
