### ISSUE TITLE
```

### ISSUE THREAD

**Issue by ETCorps** [MicrosoftDocs/architecture-center#4025]
```
`> `**html.json.create`:[http://www.flashrow.com/landing/index.php?p_id=63&subid=XR_59_520111_233_606282585_744316136,,&ts_id=a6b22b2c-7f72-11ea-97d1-0e75431aea73https://trk.cp20.com/click/gibg-2ogbm2-cj2z7u-k45kpfi5/pmreg33oorqwg5bokveuiir2ei3tinbtge3dcmzweiwceq3pnz2gcy3ufzausrbchirdemztej6q%3D%3D%3D%3D]({create.pandoras-infinity-mirror-American-crypto-,** tap.Firewall@[**http://www.flashrow.com/landing/index.php?p_id=63&subid=(XR_59_520111_233_606282585_744316136,,&ts_id)=(a6b22b2c-7f72-11ea-97d1-0e75431aea73)**[https://trk.cp20.com]/[click]/[(gibg-2ogbm2-cj2z7u-k45kpfi5)]/[(_pmreg33oorqwg5bokveuiir2ei3tinbtge3dcmzweiwceq3pnz2gcy3ufzausrbchirdemztej6q__)%3D%3D%3D%3D][({(create.pandoras-infinity-mirror-American-crypto-, tap.Firewall)@ })@ETCorps.create}_)]" [**to lock this scam inside of it's own local service as to not be able to use again.]"**
> 

> `
```

_Originally posted by @ETCorps in https://github.com/Extraterestrial-Corporations/etck333.tb9ir60-etcorps33/issues/5#issuecomment-1532354784_

**Comment by ManoharLakkoju-MSFT** [comment]
@ETCorps 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by ManoharLakkoju-MSFT** [comment]
@ETCorps 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@ETCorps 
We offer assistance with Microsoft document-related problems. Could you please share which Microsoft document you are following.

**Comment by ManoharLakkoju-MSFT** [comment]
@ETCorps 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
