### ISSUE TITLE
Link to sample code is not working

### ISSUE THREAD

**Issue by vaneyckensteven** [MicrosoftDocs/architecture-center#4040]
The sample code link returns the following error: 

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:829f4141-c01e-009d-45ee-839742000000 Time:2023-05-11T09:53:48.1180926Z</Message>
</Error>

As such the sample can not be download to try out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67cc1961-626e-f10c-18e6-bff804c1d4e5
* Version Independent ID: 70a0df7d-9990-a3f5-8812-918b9a7f1039
* Content: [Homomorphic encryption with SEAL - Azure Example Scenarios](https://learn.microsoft.com/en-us/azure/architecture/solution-ideas/articles/homomorphic-encryption-seal)
* Content Source: [docs/solution-ideas/articles/homomorphic-encryption-seal.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/solution-ideas/articles/homomorphic-encryption-seal.yml)
* Service: **architecture-center**
* Sub-service: **solution-idea**
* GitHub Login: @jocontr
* Microsoft Alias: **jocontr**

**Comment by SaibabaBalapur-MSFT** [comment]
@vaneyckensteven r
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-fearam** [comment]
Hi @vaneyckensteven

Sorry for the delay. 

[The issue was already reported and solved](https://github.com/MicrosoftDocs/architecture-center/issues/3991). The link to the example [was removed](https://github.com/MicrosoftDocs/architecture-center/commit/719bea918a4f03c9f9261b7c1b2b252e3ecd1be3). 


I will close the ticket, but feel free to open a new one if you still have concerns.

#please-close
