### ISSUE TITLE
https://www.extraterestrial-enterprises.org; extraterestrial1@outlook.com.chaisfitzwater@gmail.com; Fuck Them.0x9f5c37e0fd9bf729b1f0a6f39ce57be5e9bfd435; https://api.blockchair.com/ethereum/erc-20/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2/stats/Dhacm.AHZI6VRMNS2Q99EIYBYE23377MH8K{(@Orpheusangels33)\\html)\; https://www.extraterestrial-enterprises.org[chaisfitzwater@gmail.com] extraterestrial1@outlook.com}

### ISSUE THREAD

**Issue by ETCorps** [MicrosoftDocs/architecture-center#4043]
https://www.extraterestrial-enterprises.org; extraterestrial1@outlook.com.chaisfitzwater@gmail.com; Fuck Them.0x9f5c37e0fd9bf729b1f0a6f39ce57be5e9bfd435; https://api.blockchair.com/ethereum/erc-20/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2/stats/Dhacm.AHZI6VRMNS2Q99EIYBYE23377MH8K{(@Orpheusangels33)\\html)\; https://www.extraterestrial-enterprises.org[chaisfitzwater@gmail.com] extraterestrial1@outlook.com}

**Comment by YashikaTyagii** [comment]
@ETCorps 
Thank you for your feedback!

Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
