### ISSUE TITLE
Should decision tree be at the top of the article?

### ISSUE THREAD

**Issue by cynthn** [MicrosoftDocs/architecture-center#4049]
I feel like the decision tree should be higher up in the article. It's super useful, but it is kind of buried?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 936c85d9-c953-2def-c399-77cbda32b24d
* Version Independent ID: 9173c834-2c40-9169-b13b-6273759a2c8a
* Content: [Load-balancing options - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/technology-choices/load-balancing-overview)
* Content Source: [docs/guide/technology-choices/load-balancing-overview.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/technology-choices/load-balancing-overview.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by ckittel** [comment]
Tough call, since a lot of the nodes in the decision tree have specific definitions that were defined above the tree.  Neither is great, learners don't know why we are describing concepts to tie it into a tree later how it currently is.  If the tree is first, they might not know what the concept was we were branching on.  I will say, at least for consistency sake if nothing else, moving the tree up higher would make sense.  I think most of our chooser articles, if they have an image, it's "above the fold."

**Comment by YashikaTyagii** [comment]
@cynthn 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 92053 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
