### ISSUE TITLE
`openai-python-enterprise-logging` doesn't seem to work with GPT-4 models

### ISSUE THREAD

**Issue by ericthomas1** [MicrosoftDocs/architecture-center#4073]
Hello,

I implemented the [openai-python-enterprise-logging](https://github.com/Azure-Samples/openai-python-enterprise-logging) solution over two weeks ago. It does not seem to be working with GPT-4 models.

I documented it [here](https://github.com/Azure-Samples/openai-python-enterprise-logging/issues/8), but have not received an answer yet. While waiting, we are paying for APIM and trying to find alternative logging means.

Could you forward this to the right people?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59e64035-d0cb-d2cf-0848-4153b5cfe876
* Version Independent ID: 59e64035-d0cb-d2cf-0848-4153b5cfe876
* Content: [Implement logging and monitoring for Azure OpenAI large language models - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/ai/log-monitor-azure-openai)
* Content Source: [docs/example-scenario/ai/log-monitor-azure-openai.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/example-scenario/ai/log-monitor-azure-openai.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @jakeatmsft
* Microsoft Alias: **jacwang**

**Comment by SaibabaBalapur-MSFT** [comment]
@ericthomas1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by jakeatmsft** [comment]
Apologies for the delay.  If you are using gpt-4 32k token prompts, the APIM logging will not be able to capture the complete prompt and response due to the 8k limit on payload size.  Alternatively, you can use an APIM policy to forward logs to eventhub and send metrics back to Azure Monitor for analysis.  My colleague has a great post outlining this approach: 

link: https://journeyofthegeek.com/2023/05/18/granular-chargebacks-in-azure-openai-service/
Policy Link: https://github.com/mattfeltonma/azure-openai-apim/blob/main/apim-policies/apim-policy-event-hub-logging.xml
