### ISSUE TITLE
Deployment complexity

### ISSUE THREAD

**Issue by ramuvr** [MicrosoftDocs/architecture-center#4185]
In the Isolation model section, it says "Deployment complexity" Highly complex for independent B2C tenant. This is wrong. It is in fact nothing different to deploy one tenant or 1000, similar to how subscriptions are. Initially MS used go advise customers to maintain one subscription, now you have come to the Subscription democratization concept, similarly deployment complexity of one or multiple tenants is the same. Operation complexity is a different item in the table, so don't want to discuss it here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf468764-5ad6-37a9-9a57-384e791bc94a
* Version Independent ID: bf468764-5ad6-37a9-9a57-384e791bc94a
* Content: [Using Azure Active Directory B2C in a multitenant architecture - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/service/azure-ad-b2c)
* Content Source: [docs/guide/multitenant/service/azure-ad-b2c.md](https://github.com/microsoftdocs/architecture-center/blob/main/docs/guide/multitenant/service/azure-ad-b2c.md)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @landonpierce
* Microsoft Alias: **landonpierce**

**Comment by Naveenommi-MSFT** [comment]
@ramuvr 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by landonpierce** [comment]
Hi @ramuvr, thanks for the feedback!

Deployment complexity with Azure AD B2C scales with the number of B2C tenants you deploy mainly due to the [limit](https://learn.microsoft.com/en-us/azure/active-directory-b2c/service-limits?pivots=b2c-user-flow#azure-ad-b2c-configuration-limits) on the number of B2C tenants per Azure subscription. If you have more than the limit allows for one subscription, you must have an appropriate [bin packing](https://learn.microsoft.com/en-us/azure/architecture/guide/multitenant/approaches/resource-organization#bin-packing) strategy to "load balance" your tenants across more than one subscription. 


This is called out in the Azure AD B2C considerations for multitenancy doc, but I do think it could be clearer how it connects to the deployment complexity point in the table. We've added an item on our backlog to update the article. Thanks for bringing this to our attention!

#please-close
