### ISSUE TITLE
Machine Learning Pipeline usage

### ISSUE THREAD

**Issue by eftech13** [MicrosoftDocs/architecture-center#4222]
I have questions on the step number 2, "A preconfigured pipeline in Azure Machine Learning".
I was wondering what this step should do ?
Since what i understand, the video will be split into frames, and then the image will be classified/detection using the Azure Vision AI.
So the detection is in the Azure Vision.
What is the purposed machine learning on step number 2 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8baf9729-fadf-83d7-e449-50a1b98e8159
* Version Independent ID: 8baf9729-fadf-83d7-e449-50a1b98e8159
* Content: [Analyze video content with Computer Vision and Azure Machine Learning - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/ai-ml/architecture/analyze-video-computer-vision-machine-learning)
* Content Source: [docs/ai-ml/architecture/analyze-video-computer-vision-machine-learning.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/ai-ml/architecture/analyze-video-computer-vision-machine-learning.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @OscarSH
* Microsoft Alias: **oscarsh**

**Comment by AjayBathini-MSFT** [comment]
@eftech13 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by oscarsk16** [comment]
The pipeline in AML is pre-configured so that we are automating some notebooks where we've previously wrote some code which is able to handle the decomposition of frames. The code was written in Python and is using ffmpeg. The rest of the statement "the video will be split into frames, and then the image will be classified/detection using the Azure Vision AI.
So the detection is in the Azure Vision" is correct. AML pipeline is only used to orchestrate the notebooks.

**Comment by mike-urnun-msft** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
