### ISSUE TITLE
Visio diagram links point to the same file, rather unique files

### ISSUE THREAD

**Issue by ctsafos** [MicrosoftDocs/architecture-center#4232]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa4a3938-1142-4e18-1915-4dcee68d4c99
* Version Independent ID: aa4a3938-1142-4e18-1915-4dcee68d4c99
* Content: [Build a speech-to-text transcription pipeline to analyze recorded conversations - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/ai-ml/architecture/speech-to-text-transcription-analytics)
* Content Source: [docs/ai-ml/architecture/speech-to-text-transcription-analytics.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/ai-ml/architecture/speech-to-text-transcription-analytics.yml)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @bdleavitt
* Microsoft Alias: **bleavitt, christinas**

**Comment by SaibabaBalapur-MSFT** [comment]
@ctsafos 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ckittel** [comment]
That is correct, they do @ctsafos; the one file contains two tabs; one for each diagram.  This is by design.  Hope you find what you're looking for!

<img width="362" alt="image" src="https://github.com/MicrosoftDocs/architecture-center/assets/671075/915120f7-6ce1-45b1-b3b6-a9f4a65c25f4">

#please-close
