### ISSUE TITLE
multiregion AKS clusters is just a concept?

### ISSUE THREAD

**Issue by JeffreyVIP** [MicrosoftDocs/architecture-center#4324]
[Enter feedback here]
multiregion AKS clusters is just a concept?
In essential, 2+ standalone AKS instance in different region with some shared region-local resource like container registry.

Does my understanding correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af2806b1-1264-2775-4cce-083303e75b49
* Version Independent ID: 68218fb5-2335-183a-8469-9101a2d8a0ef
* Content: [AKS baseline for multiregion clusters - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-multi-region/aks-multi-cluster?source=docs)
* Content Source: [docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/containers/aks-multi-region/aks-multi-cluster.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @martinekuan
* Microsoft Alias: **architectures**

**Comment by RamanathanChinnappan-MSFT** [comment]
@JeffreyVIP 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by mike-urnun-msft** [comment]
> In essential, 2+ standalone AKS instance in different region with some shared region-local resource like container registry.
> Does my understanding correct?
> 
Yes, @JeffreyVIP, your understanding is correct. If you run into any issues while implementing this, feel free to post on the [MS Q&A channel](https://learn.microsoft.com/en-us/answers/index.html) instead. Since we didn't determine any faulty steps/changes to this doc upon reviewing your feedback, we will now proceed to close this thread for now. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
