### ISSUE TITLE
Uptime per described solution

### ISSUE THREAD

**Issue by agyss** [MicrosoftDocs/architecture-center#4325]
While I really like how the solutions are presented, I'm missing insights into uptime per solution. I tried looking it up and calculating it for myself and came to these numbers:

single VM: 99,9%
vm in availability zone: 99,99%
vnet, route table and public IP: 100% (really? could not find anything else)
load balancer: 99,99%
route server: 99,95%

So a setup like:
load balancer (lb) --> NVA (single) --> lb --> endpoint would be 99,99%*99,9%*99,99% or 99,8% uptime --> 89 minutes downtime/month
lb --> NVA (av zone) --> lb --> endpoint would be 99,99%*99,99%*99,99% or 99,97% uptime --> 13,39 minutes downtime/month
lb --> NVA(av zone) --> route server --> endpoint would be 99,99%*99,99%*99,95% or 99,93% --> 31.25 minutes downtime/month
NVA (av zone) with pip+udr changes --> 99,99% --> 4,46 minutes downtime/month

Now it becomes especially interesting, as the pip+udr solution may of course have the highest convergence time (which highly depends again if we talk about udr convergence which are quite fast or pip, which take longer). Some tests I did ended up being around 1 minute (but not representative --> too little data) for a pip + udr failover.

So if I now assume (just for simplicity) that a lb convergence would happen immediately and I compare the two solutions with highest availability (i.e., lb --> NVA (av zone) --> and NVA (az zone) with pip) and I ignore NVA av zone failures (as they may happen in both setups with equal likelyhood), what remains are these numbers:
8,92 minutes downtime per month on lb-->NVA-->lb setup
1 minutes downtime times the amount of expected failovers per month for the NVA pip+udr setup

So my conclusion would be that the NVA pip+udr setup provides the highest uptime (until we expect at least 9 failures per month).

So my first question would be: Are those calculations correct or did I miss something?

My second question would be: wouldn't it make sense to add those numbers to the different solutions?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bab6a90-43a3-3d83-d680-26683a3d833d
* Version Independent ID: f8eea094-d297-93e6-06ac-7652d059734f
* Content: [Deploy highly available NVAs - Azure Architecture Center](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/dmz/nva-ha#changing-pip-udr)
* Content Source: [docs/reference-architectures/dmz/nva-ha.yml](https://github.com/microsoftdocs/architecture-center/blob/main/docs/reference-architectures/dmz/nva-ha.yml)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **telmosampaio, kmayer**

**Comment by MayankBargali-MSFT** [comment]
@agyss MicrosoftDocs Github issue is mainly related to the document issue. If this is not the case I would recommend you to create a thread on the forums - [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) or [Stack Overflow](https://stackoverflow.com/)
Once you post your issue on forums, it will have visibility across the community which is a better suited audience for such types of issues.

I will go ahead and close this issue.

**Comment by agyss** [comment]
@MayankBargali-MSFT can you please tell me why the request to add these numbers to the documentation is not a documentation issue?

**Comment by ckittel** [comment]
I agree with @agyss to have additional clarity, reopening.

**Comment by stephen-sumner** [comment]
@telmosampaio - I'm curious to get your thoughts on this feedback. The math appears to generally check out. But does it prompt any ideas to update the guidance to provide more clarity. I'm not suggestion we put the SLAs in the doc and do the math since these change. 

Perhaps we can add a little bit more decision guidance. What solution should I pick and when? Perhaps we include uptime/downtime in that decision criteria. Thoughts?

cc: robotechredmond

**Comment by stephen-sumner** [comment]
@agyss - SLAs are contractual agreements and aren't the same thing as guaranteed uptime. So, for example, a 100% SLA doesn't mean the service is going to be available 100% of the time. It just means the company agrees to back that offering and provide the stated remediation if it's not 100% available. Because SLAs change and have contractual implications, we tend not to publish those in our docs, but rather refer customers to the source documentation: https://www.microsoft.com/licensing/docs/view/Service-Level-Agreements-SLA-for-Online-Services?lang=1

**Comment by skabou** [comment]
Thank you for your feedback.  We have created internal ticket 196637 to track and investigate this issue.

**Comment by skabou** [comment]
#please-close
