### ISSUE TITLE
Modern analytics architecture with Azure Databricks Implementation consideration and pricing

### ISSUE THREAD

**Issue by pchow18** [MicrosoftDocs/architecture-center#4398]
Hi I'd be interested in getting advice on implementing the azure databricks architecture you have designed.  Can this be staged?  how would you make the decision on what components when? 

Also, what is the pricing model?  

How does this all fit in with microsoft fabric? 

Thanks
Paul.

**Comment by ckittel** [comment]
Wonderful to hear about your interest in Azure Databricks. Unfortunately, this GitHub repo's issue list is to report issues with the content so that the content team can correct it (think, typos, misinformation, etc).  For getting advice on workloads in Azure, you'll need to work with a Cloud Solution Architect, or similar to understand your needs and help you walk through the design process, including evaluating resources.

Azure Architecture Center does include decision trees that can help you narrow initial component selection: <https://learn.microsoft.com/azure/architecture/guide/technology-choices/technology-choices-overview>

For pricing, please use the pricing calculator to get a good idea of how prices scale with various consumption models: <https://azure.microsoft.com/pricing/calculator/>.

This is about as far as our team can take you. Best wishes!

#please-close
